---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 08
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_08
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 09
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_09
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 10
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_10
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 11
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_11
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 12
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_12
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 13
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_13
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 14
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_14
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 15
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	CP_NRELM AS NRELM,
	CP_NRELA AS NRELA,
	CP_NLRGM AS NLRGM,
	CP_NLRGA AS NLRGA,
	CP_NSMLM AS NSMLM,
	CP_NSMLA AS NSMLA,
	CP_NACCBLOT AS NACCBLOT,
	CP_NPBITF AS NPBITF,
	CP_NTBITF AS NTBITF,
	CP_NPCPF AS NPCPF,
	CP_NTCPF AS NTCPF,
	CP_NMAUF AS NMAUF,
	CP_NCPMBLOT AS NCPMBLOT,
	CP_NCPABLOT AS NCPABLOT,
	CP_NMAUMBLOT AS NMAUMBLOT,
	CP_NMAUABLOT AS NMAUABLOT,
	CP_SIZEPS AS SIZEPS,
	CP_SIZEDS AS SIZEDS,
	CP_SIZERS AS SIZERS,
	CP_NFORLAPZ AS NFORLAPZ,
	CP_NFORLAPT AS NFORLAPT,
	CP_NFORLMAN AS NFORLMAN,
	CP_NNOREC AS NNOREC


FROM
    dc.DC_E_CMN_STS_TOT_RAW_15
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

