---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	HNDOVER_NHNDEBSTOT AS NHNDEBSTOT,
	HNDOVER_NHNDRQDTOT AS NHNDRQDTOT,
	HNDOVER_NHNDREQTOT AS NHNDREQTOT,
	HNDOVER_NHNDREQSUCC AS NHNDREQSUCC,
	HNDOVER_NHNDCMDTOT AS NHNDCMDTOT,
	HNDOVER_NHNDIBSSUCC AS NHNDIBSSUCC,
	HNDOVER_NHNDEBSSUCC AS NHNDEBSSUCC,
	HNDOVER_NHNDBSSSUCC AS NHNDBSSSUCC,
	HNDOVER_NHNDTGSSUCC AS NHNDTGSSUCC,
	HNDOVER_NHNDDGSSUCC AS NHNDDGSSUCC,
	HNDOVER_NHNDCGSSUCC AS NHNDCGSSUCC,
	HNDOVER_NHNDATTSUCC AS NHNDATTSUCC,
	HNDOVER_NHNDRELERR AS NHNDRELERR,
	HNDOVER_NHNDBSSTOT AS NHNDBSSTOT,
	HNDOVER_NHNDESHTOT AS NHNDESHTOT,
	HNDOVER_NHNDESHSUCC AS NHNDESHSUCC,
	HNDOVER_NHNDSDHTOT AS NHNDSDHTOT,
	HNDOVER_NHNDSDHSUCC AS NHNDSDHSUCC,
	HNDOVER_NHNDESTTOT AS NHNDESTTOT,
	HNDOVER_NHNDESTSUCC AS NHNDESTSUCC,
	HNDOVER_NHNDSHTTOT AS NHNDSHTTOT,
	HNDOVER_NHNDSHTSUCC AS NHNDSHTSUCC,
	HNDOVER_HNDSYNER AS HNDSYNER
FROM
    dc.DC_E_CNAXE_MSC_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	HNDOVER_NHNDEBSTOT AS NHNDEBSTOT,
	HNDOVER_NHNDRQDTOT AS NHNDRQDTOT,
	HNDOVER_NHNDREQTOT AS NHNDREQTOT,
	HNDOVER_NHNDREQSUCC AS NHNDREQSUCC,
	HNDOVER_NHNDCMDTOT AS NHNDCMDTOT,
	HNDOVER_NHNDIBSSUCC AS NHNDIBSSUCC,
	HNDOVER_NHNDEBSSUCC AS NHNDEBSSUCC,
	HNDOVER_NHNDBSSSUCC AS NHNDBSSSUCC,
	HNDOVER_NHNDTGSSUCC AS NHNDTGSSUCC,
	HNDOVER_NHNDDGSSUCC AS NHNDDGSSUCC,
	HNDOVER_NHNDCGSSUCC AS NHNDCGSSUCC,
	HNDOVER_NHNDATTSUCC AS NHNDATTSUCC,
	HNDOVER_NHNDRELERR AS NHNDRELERR,
	HNDOVER_NHNDBSSTOT AS NHNDBSSTOT,
	HNDOVER_NHNDESHTOT AS NHNDESHTOT,
	HNDOVER_NHNDESHSUCC AS NHNDESHSUCC,
	HNDOVER_NHNDSDHTOT AS NHNDSDHTOT,
	HNDOVER_NHNDSDHSUCC AS NHNDSDHSUCC,
	HNDOVER_NHNDESTTOT AS NHNDESTTOT,
	HNDOVER_NHNDESTSUCC AS NHNDESTSUCC,
	HNDOVER_NHNDSHTTOT AS NHNDSHTTOT,
	HNDOVER_NHNDSHTSUCC AS NHNDSHTSUCC,
	HNDOVER_HNDSYNER AS HNDSYNER
FROM
    dc.DC_E_CNAXE_MSC_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	HNDOVER_NHNDEBSTOT AS NHNDEBSTOT,
	HNDOVER_NHNDRQDTOT AS NHNDRQDTOT,
	HNDOVER_NHNDREQTOT AS NHNDREQTOT,
	HNDOVER_NHNDREQSUCC AS NHNDREQSUCC,
	HNDOVER_NHNDCMDTOT AS NHNDCMDTOT,
	HNDOVER_NHNDIBSSUCC AS NHNDIBSSUCC,
	HNDOVER_NHNDEBSSUCC AS NHNDEBSSUCC,
	HNDOVER_NHNDBSSSUCC AS NHNDBSSSUCC,
	HNDOVER_NHNDTGSSUCC AS NHNDTGSSUCC,
	HNDOVER_NHNDDGSSUCC AS NHNDDGSSUCC,
	HNDOVER_NHNDCGSSUCC AS NHNDCGSSUCC,
	HNDOVER_NHNDATTSUCC AS NHNDATTSUCC,
	HNDOVER_NHNDRELERR AS NHNDRELERR,
	HNDOVER_NHNDBSSTOT AS NHNDBSSTOT,
	HNDOVER_NHNDESHTOT AS NHNDESHTOT,
	HNDOVER_NHNDESHSUCC AS NHNDESHSUCC,
	HNDOVER_NHNDSDHTOT AS NHNDSDHTOT,
	HNDOVER_NHNDSDHSUCC AS NHNDSDHSUCC,
	HNDOVER_NHNDESTTOT AS NHNDESTTOT,
	HNDOVER_NHNDESTSUCC AS NHNDESTSUCC,
	HNDOVER_NHNDSHTTOT AS NHNDSHTTOT,
	HNDOVER_NHNDSHTSUCC AS NHNDSHTSUCC,
	HNDOVER_HNDSYNER AS HNDSYNER
FROM
    dc.DC_E_CNAXE_MSC_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	HNDOVER_NHNDEBSTOT AS NHNDEBSTOT,
	HNDOVER_NHNDRQDTOT AS NHNDRQDTOT,
	HNDOVER_NHNDREQTOT AS NHNDREQTOT,
	HNDOVER_NHNDREQSUCC AS NHNDREQSUCC,
	HNDOVER_NHNDCMDTOT AS NHNDCMDTOT,
	HNDOVER_NHNDIBSSUCC AS NHNDIBSSUCC,
	HNDOVER_NHNDEBSSUCC AS NHNDEBSSUCC,
	HNDOVER_NHNDBSSSUCC AS NHNDBSSSUCC,
	HNDOVER_NHNDTGSSUCC AS NHNDTGSSUCC,
	HNDOVER_NHNDDGSSUCC AS NHNDDGSSUCC,
	HNDOVER_NHNDCGSSUCC AS NHNDCGSSUCC,
	HNDOVER_NHNDATTSUCC AS NHNDATTSUCC,
	HNDOVER_NHNDRELERR AS NHNDRELERR,
	HNDOVER_NHNDBSSTOT AS NHNDBSSTOT,
	HNDOVER_NHNDESHTOT AS NHNDESHTOT,
	HNDOVER_NHNDESHSUCC AS NHNDESHSUCC,
	HNDOVER_NHNDSDHTOT AS NHNDSDHTOT,
	HNDOVER_NHNDSDHSUCC AS NHNDSDHSUCC,
	HNDOVER_NHNDESTTOT AS NHNDESTTOT,
	HNDOVER_NHNDESTSUCC AS NHNDESTSUCC,
	HNDOVER_NHNDSHTTOT AS NHNDSHTTOT,
	HNDOVER_NHNDSHTSUCC AS NHNDSHTSUCC,
	HNDOVER_HNDSYNER AS HNDSYNER
FROM
    dc.DC_E_CNAXE_MSC_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	HNDOVER_NHNDEBSTOT AS NHNDEBSTOT,
	HNDOVER_NHNDRQDTOT AS NHNDRQDTOT,
	HNDOVER_NHNDREQTOT AS NHNDREQTOT,
	HNDOVER_NHNDREQSUCC AS NHNDREQSUCC,
	HNDOVER_NHNDCMDTOT AS NHNDCMDTOT,
	HNDOVER_NHNDIBSSUCC AS NHNDIBSSUCC,
	HNDOVER_NHNDEBSSUCC AS NHNDEBSSUCC,
	HNDOVER_NHNDBSSSUCC AS NHNDBSSSUCC,
	HNDOVER_NHNDTGSSUCC AS NHNDTGSSUCC,
	HNDOVER_NHNDDGSSUCC AS NHNDDGSSUCC,
	HNDOVER_NHNDCGSSUCC AS NHNDCGSSUCC,
	HNDOVER_NHNDATTSUCC AS NHNDATTSUCC,
	HNDOVER_NHNDRELERR AS NHNDRELERR,
	HNDOVER_NHNDBSSTOT AS NHNDBSSTOT,
	HNDOVER_NHNDESHTOT AS NHNDESHTOT,
	HNDOVER_NHNDESHSUCC AS NHNDESHSUCC,
	HNDOVER_NHNDSDHTOT AS NHNDSDHTOT,
	HNDOVER_NHNDSDHSUCC AS NHNDSDHSUCC,
	HNDOVER_NHNDESTTOT AS NHNDESTTOT,
	HNDOVER_NHNDESTSUCC AS NHNDESTSUCC,
	HNDOVER_NHNDSHTTOT AS NHNDSHTTOT,
	HNDOVER_NHNDSHTSUCC AS NHNDSHTSUCC,
	HNDOVER_HNDSYNER AS HNDSYNER
FROM
    dc.DC_E_CNAXE_MSC_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	HNDOVER_NHNDEBSTOT AS NHNDEBSTOT,
	HNDOVER_NHNDRQDTOT AS NHNDRQDTOT,
	HNDOVER_NHNDREQTOT AS NHNDREQTOT,
	HNDOVER_NHNDREQSUCC AS NHNDREQSUCC,
	HNDOVER_NHNDCMDTOT AS NHNDCMDTOT,
	HNDOVER_NHNDIBSSUCC AS NHNDIBSSUCC,
	HNDOVER_NHNDEBSSUCC AS NHNDEBSSUCC,
	HNDOVER_NHNDBSSSUCC AS NHNDBSSSUCC,
	HNDOVER_NHNDTGSSUCC AS NHNDTGSSUCC,
	HNDOVER_NHNDDGSSUCC AS NHNDDGSSUCC,
	HNDOVER_NHNDCGSSUCC AS NHNDCGSSUCC,
	HNDOVER_NHNDATTSUCC AS NHNDATTSUCC,
	HNDOVER_NHNDRELERR AS NHNDRELERR,
	HNDOVER_NHNDBSSTOT AS NHNDBSSTOT,
	HNDOVER_NHNDESHTOT AS NHNDESHTOT,
	HNDOVER_NHNDESHSUCC AS NHNDESHSUCC,
	HNDOVER_NHNDSDHTOT AS NHNDSDHTOT,
	HNDOVER_NHNDSDHSUCC AS NHNDSDHSUCC,
	HNDOVER_NHNDESTTOT AS NHNDESTTOT,
	HNDOVER_NHNDESTSUCC AS NHNDESTSUCC,
	HNDOVER_NHNDSHTTOT AS NHNDSHTTOT,
	HNDOVER_NHNDSHTSUCC AS NHNDSHTSUCC,
	HNDOVER_HNDSYNER AS HNDSYNER
FROM
    dc.DC_E_CNAXE_MSC_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	HNDOVER_NHNDEBSTOT AS NHNDEBSTOT,
	HNDOVER_NHNDRQDTOT AS NHNDRQDTOT,
	HNDOVER_NHNDREQTOT AS NHNDREQTOT,
	HNDOVER_NHNDREQSUCC AS NHNDREQSUCC,
	HNDOVER_NHNDCMDTOT AS NHNDCMDTOT,
	HNDOVER_NHNDIBSSUCC AS NHNDIBSSUCC,
	HNDOVER_NHNDEBSSUCC AS NHNDEBSSUCC,
	HNDOVER_NHNDBSSSUCC AS NHNDBSSSUCC,
	HNDOVER_NHNDTGSSUCC AS NHNDTGSSUCC,
	HNDOVER_NHNDDGSSUCC AS NHNDDGSSUCC,
	HNDOVER_NHNDCGSSUCC AS NHNDCGSSUCC,
	HNDOVER_NHNDATTSUCC AS NHNDATTSUCC,
	HNDOVER_NHNDRELERR AS NHNDRELERR,
	HNDOVER_NHNDBSSTOT AS NHNDBSSTOT,
	HNDOVER_NHNDESHTOT AS NHNDESHTOT,
	HNDOVER_NHNDESHSUCC AS NHNDESHSUCC,
	HNDOVER_NHNDSDHTOT AS NHNDSDHTOT,
	HNDOVER_NHNDSDHSUCC AS NHNDSDHSUCC,
	HNDOVER_NHNDESTTOT AS NHNDESTTOT,
	HNDOVER_NHNDESTSUCC AS NHNDESTSUCC,
	HNDOVER_NHNDSHTTOT AS NHNDSHTTOT,
	HNDOVER_NHNDSHTSUCC AS NHNDSHTSUCC,
	HNDOVER_HNDSYNER AS HNDSYNER
FROM
    dc.DC_E_CNAXE_MSC_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

