---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 08
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_08
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 09
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_09
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 10
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_10
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 11
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_11
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 12
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_12
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 13
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_13
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 14
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_14
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 15
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	LOAS_ACCLOAD AS ACCLOAD,
	LOAS_NSCAN AS NSCAN,
	LOAS_NOFFORG AS NOFFORG,
	LOAS_NOFFIEX AS NOFFIEX,
	LOAS_NFTDORG AS NFTDORG,
	LOAS_NFTDIEX AS NFTDIEX,
	LOAS_NOFFMLO AS NOFFMLO,
	LOAS_NOFFMHI AS NOFFMHI,
	LOAS_NFTDMLO AS NFTDMLO,
	LOAS_NFTDMHI AS NFTDMHI,
	LOAS_NCAPREQCNT AS NCAPREQCNT,
	LOAS_NCAPREJCNT AS NCAPREJCNT,
	LOAS_NOFFPRIO AS NOFFPRIO,
	LOAS_NOFFNPRIO AS NOFFNPRIO,
	LOAS_NFTDPRIO AS NFTDPRIO,
	LOAS_NFTDNPRIO AS NFTDNPRIO,
	LOAS_NOFFTCAP AS NOFFTCAP,
	LOAS_NFTDTCAP AS NFTDTCAP
FROM
    dc.DC_E_CMN_STS_TOT_RAW_15
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

