---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCLST_NNBRHBANTOT AS NNBRHBANTOT,
	NBRMSCLST_NNBRHBANSUCC AS NNBRHBANSUCC,
	NBRMSCLST_NNBRHSANTOT AS NNBRHSANTOT,
	NBRMSCLST_NNBRHSANSUCC AS NNBRHSANSUCC,
	NBRMSCLST_NNBRHTHITOT AS NNBRHTHITOT,
	NBRMSCLST_NNBRHTHISUCC AS NNBRHTHISUCC,
	NBRMSCLST_NNBRHINATOT AS NNBRHINATOT,
	NBRMSCLST_NNBRHINASUCC AS NNBRHINASUCC,
	NBRMSCLST_NNBRHSNATOT AS NNBRHSNATOT,
	NBRMSCLST_NNBRHSNASUCC AS NNBRHSNASUCC,
	NBRMSCLST_NNBRHBSTTOT AS NNBRHBSTTOT,
	NBRMSCLST_NNBRHBSTSUCC AS NNBRHBSTSUCC,
	NBRMSCLST_NNBRHBTTTOT AS NNBRHBTTTOT,
	NBRMSCLST_NNBRHBTTSUCC AS NNBRHBTTSUCC,
	NBRMSCLST_NNBRHBAOSDHTOT AS NNBRHBAOSDHTOT,
	NBRMSCLST_NNBRHBAOSDHSUCC AS NNBRHBAOSDHSUCC,
	NBRMSCLST_NNBRHSISDHTOT AS NNBRHSISDHTOT,
	NBRMSCLST_NNBRHSISDHSUCC AS NNBRHSISDHSUCC,
	NBRMSCLST_NNBRHTHISDHTOT AS NNBRHTHISDHTOT,
	NBRMSCLST_NNBRHTHISDHSUCC AS NNBRHTHISDHSUCC,
	NBRMSCLST_NNBRHBAISDHTOT AS NNBRHBAISDHTOT,
	NBRMSCLST_NNBRHBAISDHSUCC AS NNBRHBAISDHSUCC,
    NBRMSCLST_NNBRHSOSDHTOT AS NNBRHSOSDHTOT,
	NBRMSCLST_NNBRHSOSDHSUCC AS NNBRHSOSDHSUCC,
	NBRMSCLST_NNBRSCHASTOT AS NNBRSCHASTOT,
	NBRMSCLST_NNBRSCHASSUCC AS NNBRSCHASSUCC,
	NBRMSCLST_NNBRSCHARTOT AS NNBRSCHARTOT,
	NBRMSCLST_NNBRSCHARSUCC AS NNBRSCHARSUCC,
	NBRMSCLST_NNSCHATOT AS NNSCHATOT,
	NBRMSCLST_NNSCHASUCC AS NNSCHASUCC
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCLST_NNBRHBANTOT AS NNBRHBANTOT,
	NBRMSCLST_NNBRHBANSUCC AS NNBRHBANSUCC,
	NBRMSCLST_NNBRHSANTOT AS NNBRHSANTOT,
	NBRMSCLST_NNBRHSANSUCC AS NNBRHSANSUCC,
	NBRMSCLST_NNBRHTHITOT AS NNBRHTHITOT,
	NBRMSCLST_NNBRHTHISUCC AS NNBRHTHISUCC,
	NBRMSCLST_NNBRHINATOT AS NNBRHINATOT,
	NBRMSCLST_NNBRHINASUCC AS NNBRHINASUCC,
	NBRMSCLST_NNBRHSNATOT AS NNBRHSNATOT,
	NBRMSCLST_NNBRHSNASUCC AS NNBRHSNASUCC,
	NBRMSCLST_NNBRHBSTTOT AS NNBRHBSTTOT,
	NBRMSCLST_NNBRHBSTSUCC AS NNBRHBSTSUCC,
	NBRMSCLST_NNBRHBTTTOT AS NNBRHBTTTOT,
	NBRMSCLST_NNBRHBTTSUCC AS NNBRHBTTSUCC,
	NBRMSCLST_NNBRHBAOSDHTOT AS NNBRHBAOSDHTOT,
	NBRMSCLST_NNBRHBAOSDHSUCC AS NNBRHBAOSDHSUCC,
	NBRMSCLST_NNBRHSISDHTOT AS NNBRHSISDHTOT,
	NBRMSCLST_NNBRHSISDHSUCC AS NNBRHSISDHSUCC,
	NBRMSCLST_NNBRHTHISDHTOT AS NNBRHTHISDHTOT,
	NBRMSCLST_NNBRHTHISDHSUCC AS NNBRHTHISDHSUCC,
	NBRMSCLST_NNBRHBAISDHTOT AS NNBRHBAISDHTOT,
	NBRMSCLST_NNBRHBAISDHSUCC AS NNBRHBAISDHSUCC,
    NBRMSCLST_NNBRHSOSDHTOT AS NNBRHSOSDHTOT,
	NBRMSCLST_NNBRHSOSDHSUCC AS NNBRHSOSDHSUCC,
	NBRMSCLST_NNBRSCHASTOT AS NNBRSCHASTOT,
	NBRMSCLST_NNBRSCHASSUCC AS NNBRSCHASSUCC,
	NBRMSCLST_NNBRSCHARTOT AS NNBRSCHARTOT,
	NBRMSCLST_NNBRSCHARSUCC AS NNBRSCHARSUCC,
	NBRMSCLST_NNSCHATOT AS NNSCHATOT,
	NBRMSCLST_NNSCHASUCC AS NNSCHASUCC
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCLST_NNBRHBANTOT AS NNBRHBANTOT,
	NBRMSCLST_NNBRHBANSUCC AS NNBRHBANSUCC,
	NBRMSCLST_NNBRHSANTOT AS NNBRHSANTOT,
	NBRMSCLST_NNBRHSANSUCC AS NNBRHSANSUCC,
	NBRMSCLST_NNBRHTHITOT AS NNBRHTHITOT,
	NBRMSCLST_NNBRHTHISUCC AS NNBRHTHISUCC,
	NBRMSCLST_NNBRHINATOT AS NNBRHINATOT,
	NBRMSCLST_NNBRHINASUCC AS NNBRHINASUCC,
	NBRMSCLST_NNBRHSNATOT AS NNBRHSNATOT,
	NBRMSCLST_NNBRHSNASUCC AS NNBRHSNASUCC,
	NBRMSCLST_NNBRHBSTTOT AS NNBRHBSTTOT,
	NBRMSCLST_NNBRHBSTSUCC AS NNBRHBSTSUCC,
	NBRMSCLST_NNBRHBTTTOT AS NNBRHBTTTOT,
	NBRMSCLST_NNBRHBTTSUCC AS NNBRHBTTSUCC,
	NBRMSCLST_NNBRHBAOSDHTOT AS NNBRHBAOSDHTOT,
	NBRMSCLST_NNBRHBAOSDHSUCC AS NNBRHBAOSDHSUCC,
	NBRMSCLST_NNBRHSISDHTOT AS NNBRHSISDHTOT,
	NBRMSCLST_NNBRHSISDHSUCC AS NNBRHSISDHSUCC,
	NBRMSCLST_NNBRHTHISDHTOT AS NNBRHTHISDHTOT,
	NBRMSCLST_NNBRHTHISDHSUCC AS NNBRHTHISDHSUCC,
	NBRMSCLST_NNBRHBAISDHTOT AS NNBRHBAISDHTOT,
	NBRMSCLST_NNBRHBAISDHSUCC AS NNBRHBAISDHSUCC,
    NBRMSCLST_NNBRHSOSDHTOT AS NNBRHSOSDHTOT,
	NBRMSCLST_NNBRHSOSDHSUCC AS NNBRHSOSDHSUCC,
	NBRMSCLST_NNBRSCHASTOT AS NNBRSCHASTOT,
	NBRMSCLST_NNBRSCHASSUCC AS NNBRSCHASSUCC,
	NBRMSCLST_NNBRSCHARTOT AS NNBRSCHARTOT,
	NBRMSCLST_NNBRSCHARSUCC AS NNBRSCHARSUCC,
	NBRMSCLST_NNSCHATOT AS NNSCHATOT,
	NBRMSCLST_NNSCHASUCC AS NNSCHASUCC
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCLST_NNBRHBANTOT AS NNBRHBANTOT,
	NBRMSCLST_NNBRHBANSUCC AS NNBRHBANSUCC,
	NBRMSCLST_NNBRHSANTOT AS NNBRHSANTOT,
	NBRMSCLST_NNBRHSANSUCC AS NNBRHSANSUCC,
	NBRMSCLST_NNBRHTHITOT AS NNBRHTHITOT,
	NBRMSCLST_NNBRHTHISUCC AS NNBRHTHISUCC,
	NBRMSCLST_NNBRHINATOT AS NNBRHINATOT,
	NBRMSCLST_NNBRHINASUCC AS NNBRHINASUCC,
	NBRMSCLST_NNBRHSNATOT AS NNBRHSNATOT,
	NBRMSCLST_NNBRHSNASUCC AS NNBRHSNASUCC,
	NBRMSCLST_NNBRHBSTTOT AS NNBRHBSTTOT,
	NBRMSCLST_NNBRHBSTSUCC AS NNBRHBSTSUCC,
	NBRMSCLST_NNBRHBTTTOT AS NNBRHBTTTOT,
	NBRMSCLST_NNBRHBTTSUCC AS NNBRHBTTSUCC,
	NBRMSCLST_NNBRHBAOSDHTOT AS NNBRHBAOSDHTOT,
	NBRMSCLST_NNBRHBAOSDHSUCC AS NNBRHBAOSDHSUCC,
	NBRMSCLST_NNBRHSISDHTOT AS NNBRHSISDHTOT,
	NBRMSCLST_NNBRHSISDHSUCC AS NNBRHSISDHSUCC,
	NBRMSCLST_NNBRHTHISDHTOT AS NNBRHTHISDHTOT,
	NBRMSCLST_NNBRHTHISDHSUCC AS NNBRHTHISDHSUCC,
	NBRMSCLST_NNBRHBAISDHTOT AS NNBRHBAISDHTOT,
	NBRMSCLST_NNBRHBAISDHSUCC AS NNBRHBAISDHSUCC,
    NBRMSCLST_NNBRHSOSDHTOT AS NNBRHSOSDHTOT,
	NBRMSCLST_NNBRHSOSDHSUCC AS NNBRHSOSDHSUCC,
	NBRMSCLST_NNBRSCHASTOT AS NNBRSCHASTOT,
	NBRMSCLST_NNBRSCHASSUCC AS NNBRSCHASSUCC,
	NBRMSCLST_NNBRSCHARTOT AS NNBRSCHARTOT,
	NBRMSCLST_NNBRSCHARSUCC AS NNBRSCHARSUCC,
	NBRMSCLST_NNSCHATOT AS NNSCHATOT,
	NBRMSCLST_NNSCHASUCC AS NNSCHASUCC
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCLST_NNBRHBANTOT AS NNBRHBANTOT,
	NBRMSCLST_NNBRHBANSUCC AS NNBRHBANSUCC,
	NBRMSCLST_NNBRHSANTOT AS NNBRHSANTOT,
	NBRMSCLST_NNBRHSANSUCC AS NNBRHSANSUCC,
	NBRMSCLST_NNBRHTHITOT AS NNBRHTHITOT,
	NBRMSCLST_NNBRHTHISUCC AS NNBRHTHISUCC,
	NBRMSCLST_NNBRHINATOT AS NNBRHINATOT,
	NBRMSCLST_NNBRHINASUCC AS NNBRHINASUCC,
	NBRMSCLST_NNBRHSNATOT AS NNBRHSNATOT,
	NBRMSCLST_NNBRHSNASUCC AS NNBRHSNASUCC,
	NBRMSCLST_NNBRHBSTTOT AS NNBRHBSTTOT,
	NBRMSCLST_NNBRHBSTSUCC AS NNBRHBSTSUCC,
	NBRMSCLST_NNBRHBTTTOT AS NNBRHBTTTOT,
	NBRMSCLST_NNBRHBTTSUCC AS NNBRHBTTSUCC,
	NBRMSCLST_NNBRHBAOSDHTOT AS NNBRHBAOSDHTOT,
	NBRMSCLST_NNBRHBAOSDHSUCC AS NNBRHBAOSDHSUCC,
	NBRMSCLST_NNBRHSISDHTOT AS NNBRHSISDHTOT,
	NBRMSCLST_NNBRHSISDHSUCC AS NNBRHSISDHSUCC,
	NBRMSCLST_NNBRHTHISDHTOT AS NNBRHTHISDHTOT,
	NBRMSCLST_NNBRHTHISDHSUCC AS NNBRHTHISDHSUCC,
	NBRMSCLST_NNBRHBAISDHTOT AS NNBRHBAISDHTOT,
	NBRMSCLST_NNBRHBAISDHSUCC AS NNBRHBAISDHSUCC,
    NBRMSCLST_NNBRHSOSDHTOT AS NNBRHSOSDHTOT,
	NBRMSCLST_NNBRHSOSDHSUCC AS NNBRHSOSDHSUCC,
	NBRMSCLST_NNBRSCHASTOT AS NNBRSCHASTOT,
	NBRMSCLST_NNBRSCHASSUCC AS NNBRSCHASSUCC,
	NBRMSCLST_NNBRSCHARTOT AS NNBRSCHARTOT,
	NBRMSCLST_NNBRSCHARSUCC AS NNBRSCHARSUCC,
	NBRMSCLST_NNSCHATOT AS NNSCHATOT,
	NBRMSCLST_NNSCHASUCC AS NNSCHASUCC
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCLST_NNBRHBANTOT AS NNBRHBANTOT,
	NBRMSCLST_NNBRHBANSUCC AS NNBRHBANSUCC,
	NBRMSCLST_NNBRHSANTOT AS NNBRHSANTOT,
	NBRMSCLST_NNBRHSANSUCC AS NNBRHSANSUCC,
	NBRMSCLST_NNBRHTHITOT AS NNBRHTHITOT,
	NBRMSCLST_NNBRHTHISUCC AS NNBRHTHISUCC,
	NBRMSCLST_NNBRHINATOT AS NNBRHINATOT,
	NBRMSCLST_NNBRHINASUCC AS NNBRHINASUCC,
	NBRMSCLST_NNBRHSNATOT AS NNBRHSNATOT,
	NBRMSCLST_NNBRHSNASUCC AS NNBRHSNASUCC,
	NBRMSCLST_NNBRHBSTTOT AS NNBRHBSTTOT,
	NBRMSCLST_NNBRHBSTSUCC AS NNBRHBSTSUCC,
	NBRMSCLST_NNBRHBTTTOT AS NNBRHBTTTOT,
	NBRMSCLST_NNBRHBTTSUCC AS NNBRHBTTSUCC,
	NBRMSCLST_NNBRHBAOSDHTOT AS NNBRHBAOSDHTOT,
	NBRMSCLST_NNBRHBAOSDHSUCC AS NNBRHBAOSDHSUCC,
	NBRMSCLST_NNBRHSISDHTOT AS NNBRHSISDHTOT,
	NBRMSCLST_NNBRHSISDHSUCC AS NNBRHSISDHSUCC,
	NBRMSCLST_NNBRHTHISDHTOT AS NNBRHTHISDHTOT,
	NBRMSCLST_NNBRHTHISDHSUCC AS NNBRHTHISDHSUCC,
	NBRMSCLST_NNBRHBAISDHTOT AS NNBRHBAISDHTOT,
	NBRMSCLST_NNBRHBAISDHSUCC AS NNBRHBAISDHSUCC,
    NBRMSCLST_NNBRHSOSDHTOT AS NNBRHSOSDHTOT,
	NBRMSCLST_NNBRHSOSDHSUCC AS NNBRHSOSDHSUCC,
	NBRMSCLST_NNBRSCHASTOT AS NNBRSCHASTOT,
	NBRMSCLST_NNBRSCHASSUCC AS NNBRSCHASSUCC,
	NBRMSCLST_NNBRSCHARTOT AS NNBRSCHARTOT,
	NBRMSCLST_NNBRSCHARSUCC AS NNBRSCHARSUCC,
	NBRMSCLST_NNSCHATOT AS NNSCHATOT,
	NBRMSCLST_NNSCHASUCC AS NNSCHASUCC
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCLST_NNBRHBANTOT AS NNBRHBANTOT,
	NBRMSCLST_NNBRHBANSUCC AS NNBRHBANSUCC,
	NBRMSCLST_NNBRHSANTOT AS NNBRHSANTOT,
	NBRMSCLST_NNBRHSANSUCC AS NNBRHSANSUCC,
	NBRMSCLST_NNBRHTHITOT AS NNBRHTHITOT,
	NBRMSCLST_NNBRHTHISUCC AS NNBRHTHISUCC,
	NBRMSCLST_NNBRHINATOT AS NNBRHINATOT,
	NBRMSCLST_NNBRHINASUCC AS NNBRHINASUCC,
	NBRMSCLST_NNBRHSNATOT AS NNBRHSNATOT,
	NBRMSCLST_NNBRHSNASUCC AS NNBRHSNASUCC,
	NBRMSCLST_NNBRHBSTTOT AS NNBRHBSTTOT,
	NBRMSCLST_NNBRHBSTSUCC AS NNBRHBSTSUCC,
	NBRMSCLST_NNBRHBTTTOT AS NNBRHBTTTOT,
	NBRMSCLST_NNBRHBTTSUCC AS NNBRHBTTSUCC,
	NBRMSCLST_NNBRHBAOSDHTOT AS NNBRHBAOSDHTOT,
	NBRMSCLST_NNBRHBAOSDHSUCC AS NNBRHBAOSDHSUCC,
	NBRMSCLST_NNBRHSISDHTOT AS NNBRHSISDHTOT,
	NBRMSCLST_NNBRHSISDHSUCC AS NNBRHSISDHSUCC,
	NBRMSCLST_NNBRHTHISDHTOT AS NNBRHTHISDHTOT,
	NBRMSCLST_NNBRHTHISDHSUCC AS NNBRHTHISDHSUCC,
	NBRMSCLST_NNBRHBAISDHTOT AS NNBRHBAISDHTOT,
	NBRMSCLST_NNBRHBAISDHSUCC AS NNBRHBAISDHSUCC,
    NBRMSCLST_NNBRHSOSDHTOT AS NNBRHSOSDHTOT,
	NBRMSCLST_NNBRHSOSDHSUCC AS NNBRHSOSDHSUCC,
	NBRMSCLST_NNBRSCHASTOT AS NNBRSCHASTOT,
	NBRMSCLST_NNBRSCHASSUCC AS NNBRSCHASSUCC,
	NBRMSCLST_NNBRSCHARTOT AS NNBRSCHARTOT,
	NBRMSCLST_NNBRSCHARSUCC AS NNBRSCHARSUCC,
	NBRMSCLST_NNSCHATOT AS NNSCHATOT,
	NBRMSCLST_NNSCHASUCC AS NNSCHASUCC
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

