---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCGUH_NNGUHBTOT AS NNGUHBTOT,
	NBRMSCGUH_NNGUHBSUCC AS NNGUHBSUCC,
	NBRMSCGUH_NNGUHATOT AS NNGUHATOT,
	NBRMSCGUH_NNGUHASUCC AS NNGUHASUCC,
	NBRMSCGUH_NNGUHTTOT AS NNGUHTTOT,
	NBRMSCGUH_NNGUHTSUCC AS NNGUHTSUCC,
	NBRMSCGUH_NNGUHITOT AS NNGUHITOT,
	NBRMSCGUH_NNGUHISUCC AS NNGUHISUCC,
	NBRMSCGUH_NNGUSTTOT AS NNGUSTTOT,
	NBRMSCGUH_NNGUSTSUCC AS NNGUSTSUCC,
	NBRMSCGUH_NNGUHSSTOT AS NNGUHSSTOT,
	NBRMSCGUH_NNGUHSSSUCC AS NNGUHSSSUCC,
	NBRMSCGUH_NNGUHSTOT AS NNGUHSTOT,
	NBRMSCGUH_NNGUHSSUCC AS NNGUHSSUCC,
	NBRMSCGUH_NNGUHTSTOT AS NNGUHTSTOT,
	NBRMSCGUH_NNGUHTSSUCC AS NNGUHTSSUCC,
	NBRMSCGUH_NNGUHISTOT AS NNGUHISTOT,
	NBRMSCGUH_NNGUHISSUCC AS NNGUHISSUCC,
	NBRMSCGUH_NNGUSCATOT AS NNGUSCATOT,
	NBRMSCGUH_NNGSUSCASUCC AS NNGSUSCASUCC,
	NBRMSCGUH_NNGUREDREJ AS NNGUREDREJ
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCGUH_NNGUHBTOT AS NNGUHBTOT,
	NBRMSCGUH_NNGUHBSUCC AS NNGUHBSUCC,
	NBRMSCGUH_NNGUHATOT AS NNGUHATOT,
	NBRMSCGUH_NNGUHASUCC AS NNGUHASUCC,
	NBRMSCGUH_NNGUHTTOT AS NNGUHTTOT,
	NBRMSCGUH_NNGUHTSUCC AS NNGUHTSUCC,
	NBRMSCGUH_NNGUHITOT AS NNGUHITOT,
	NBRMSCGUH_NNGUHISUCC AS NNGUHISUCC,
	NBRMSCGUH_NNGUSTTOT AS NNGUSTTOT,
	NBRMSCGUH_NNGUSTSUCC AS NNGUSTSUCC,
	NBRMSCGUH_NNGUHSSTOT AS NNGUHSSTOT,
	NBRMSCGUH_NNGUHSSSUCC AS NNGUHSSSUCC,
	NBRMSCGUH_NNGUHSTOT AS NNGUHSTOT,
	NBRMSCGUH_NNGUHSSUCC AS NNGUHSSUCC,
	NBRMSCGUH_NNGUHTSTOT AS NNGUHTSTOT,
	NBRMSCGUH_NNGUHTSSUCC AS NNGUHTSSUCC,
	NBRMSCGUH_NNGUHISTOT AS NNGUHISTOT,
	NBRMSCGUH_NNGUHISSUCC AS NNGUHISSUCC,
	NBRMSCGUH_NNGUSCATOT AS NNGUSCATOT,
	NBRMSCGUH_NNGSUSCASUCC AS NNGSUSCASUCC,
	NBRMSCGUH_NNGUREDREJ AS NNGUREDREJ
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCGUH_NNGUHBTOT AS NNGUHBTOT,
	NBRMSCGUH_NNGUHBSUCC AS NNGUHBSUCC,
	NBRMSCGUH_NNGUHATOT AS NNGUHATOT,
	NBRMSCGUH_NNGUHASUCC AS NNGUHASUCC,
	NBRMSCGUH_NNGUHTTOT AS NNGUHTTOT,
	NBRMSCGUH_NNGUHTSUCC AS NNGUHTSUCC,
	NBRMSCGUH_NNGUHITOT AS NNGUHITOT,
	NBRMSCGUH_NNGUHISUCC AS NNGUHISUCC,
	NBRMSCGUH_NNGUSTTOT AS NNGUSTTOT,
	NBRMSCGUH_NNGUSTSUCC AS NNGUSTSUCC,
	NBRMSCGUH_NNGUHSSTOT AS NNGUHSSTOT,
	NBRMSCGUH_NNGUHSSSUCC AS NNGUHSSSUCC,
	NBRMSCGUH_NNGUHSTOT AS NNGUHSTOT,
	NBRMSCGUH_NNGUHSSUCC AS NNGUHSSUCC,
	NBRMSCGUH_NNGUHTSTOT AS NNGUHTSTOT,
	NBRMSCGUH_NNGUHTSSUCC AS NNGUHTSSUCC,
	NBRMSCGUH_NNGUHISTOT AS NNGUHISTOT,
	NBRMSCGUH_NNGUHISSUCC AS NNGUHISSUCC,
	NBRMSCGUH_NNGUSCATOT AS NNGUSCATOT,
	NBRMSCGUH_NNGSUSCASUCC AS NNGSUSCASUCC,
	NBRMSCGUH_NNGUREDREJ AS NNGUREDREJ
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCGUH_NNGUHBTOT AS NNGUHBTOT,
	NBRMSCGUH_NNGUHBSUCC AS NNGUHBSUCC,
	NBRMSCGUH_NNGUHATOT AS NNGUHATOT,
	NBRMSCGUH_NNGUHASUCC AS NNGUHASUCC,
	NBRMSCGUH_NNGUHTTOT AS NNGUHTTOT,
	NBRMSCGUH_NNGUHTSUCC AS NNGUHTSUCC,
	NBRMSCGUH_NNGUHITOT AS NNGUHITOT,
	NBRMSCGUH_NNGUHISUCC AS NNGUHISUCC,
	NBRMSCGUH_NNGUSTTOT AS NNGUSTTOT,
	NBRMSCGUH_NNGUSTSUCC AS NNGUSTSUCC,
	NBRMSCGUH_NNGUHSSTOT AS NNGUHSSTOT,
	NBRMSCGUH_NNGUHSSSUCC AS NNGUHSSSUCC,
	NBRMSCGUH_NNGUHSTOT AS NNGUHSTOT,
	NBRMSCGUH_NNGUHSSUCC AS NNGUHSSUCC,
	NBRMSCGUH_NNGUHTSTOT AS NNGUHTSTOT,
	NBRMSCGUH_NNGUHTSSUCC AS NNGUHTSSUCC,
	NBRMSCGUH_NNGUHISTOT AS NNGUHISTOT,
	NBRMSCGUH_NNGUHISSUCC AS NNGUHISSUCC,
	NBRMSCGUH_NNGUSCATOT AS NNGUSCATOT,
	NBRMSCGUH_NNGSUSCASUCC AS NNGSUSCASUCC,
	NBRMSCGUH_NNGUREDREJ AS NNGUREDREJ
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCGUH_NNGUHBTOT AS NNGUHBTOT,
	NBRMSCGUH_NNGUHBSUCC AS NNGUHBSUCC,
	NBRMSCGUH_NNGUHATOT AS NNGUHATOT,
	NBRMSCGUH_NNGUHASUCC AS NNGUHASUCC,
	NBRMSCGUH_NNGUHTTOT AS NNGUHTTOT,
	NBRMSCGUH_NNGUHTSUCC AS NNGUHTSUCC,
	NBRMSCGUH_NNGUHITOT AS NNGUHITOT,
	NBRMSCGUH_NNGUHISUCC AS NNGUHISUCC,
	NBRMSCGUH_NNGUSTTOT AS NNGUSTTOT,
	NBRMSCGUH_NNGUSTSUCC AS NNGUSTSUCC,
	NBRMSCGUH_NNGUHSSTOT AS NNGUHSSTOT,
	NBRMSCGUH_NNGUHSSSUCC AS NNGUHSSSUCC,
	NBRMSCGUH_NNGUHSTOT AS NNGUHSTOT,
	NBRMSCGUH_NNGUHSSUCC AS NNGUHSSUCC,
	NBRMSCGUH_NNGUHTSTOT AS NNGUHTSTOT,
	NBRMSCGUH_NNGUHTSSUCC AS NNGUHTSSUCC,
	NBRMSCGUH_NNGUHISTOT AS NNGUHISTOT,
	NBRMSCGUH_NNGUHISSUCC AS NNGUHISSUCC,
	NBRMSCGUH_NNGUSCATOT AS NNGUSCATOT,
	NBRMSCGUH_NNGSUSCASUCC AS NNGSUSCASUCC,
	NBRMSCGUH_NNGUREDREJ AS NNGUREDREJ
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCGUH_NNGUHBTOT AS NNGUHBTOT,
	NBRMSCGUH_NNGUHBSUCC AS NNGUHBSUCC,
	NBRMSCGUH_NNGUHATOT AS NNGUHATOT,
	NBRMSCGUH_NNGUHASUCC AS NNGUHASUCC,
	NBRMSCGUH_NNGUHTTOT AS NNGUHTTOT,
	NBRMSCGUH_NNGUHTSUCC AS NNGUHTSUCC,
	NBRMSCGUH_NNGUHITOT AS NNGUHITOT,
	NBRMSCGUH_NNGUHISUCC AS NNGUHISUCC,
	NBRMSCGUH_NNGUSTTOT AS NNGUSTTOT,
	NBRMSCGUH_NNGUSTSUCC AS NNGUSTSUCC,
	NBRMSCGUH_NNGUHSSTOT AS NNGUHSSTOT,
	NBRMSCGUH_NNGUHSSSUCC AS NNGUHSSSUCC,
	NBRMSCGUH_NNGUHSTOT AS NNGUHSTOT,
	NBRMSCGUH_NNGUHSSUCC AS NNGUHSSUCC,
	NBRMSCGUH_NNGUHTSTOT AS NNGUHTSTOT,
	NBRMSCGUH_NNGUHTSSUCC AS NNGUHTSSUCC,
	NBRMSCGUH_NNGUHISTOT AS NNGUHISTOT,
	NBRMSCGUH_NNGUHISSUCC AS NNGUHISSUCC,
	NBRMSCGUH_NNGUSCATOT AS NNGUSCATOT,
	NBRMSCGUH_NNGSUSCASUCC AS NNGSUSCASUCC,
	NBRMSCGUH_NNGUREDREJ AS NNGUREDREJ
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBRMSCGUH_NNGUHBTOT AS NNGUHBTOT,
	NBRMSCGUH_NNGUHBSUCC AS NNGUHBSUCC,
	NBRMSCGUH_NNGUHATOT AS NNGUHATOT,
	NBRMSCGUH_NNGUHASUCC AS NNGUHASUCC,
	NBRMSCGUH_NNGUHTTOT AS NNGUHTTOT,
	NBRMSCGUH_NNGUHTSUCC AS NNGUHTSUCC,
	NBRMSCGUH_NNGUHITOT AS NNGUHITOT,
	NBRMSCGUH_NNGUHISUCC AS NNGUHISUCC,
	NBRMSCGUH_NNGUSTTOT AS NNGUSTTOT,
	NBRMSCGUH_NNGUSTSUCC AS NNGUSTSUCC,
	NBRMSCGUH_NNGUHSSTOT AS NNGUHSSTOT,
	NBRMSCGUH_NNGUHSSSUCC AS NNGUHSSSUCC,
	NBRMSCGUH_NNGUHSTOT AS NNGUHSTOT,
	NBRMSCGUH_NNGUHSSUCC AS NNGUHSSUCC,
	NBRMSCGUH_NNGUHTSTOT AS NNGUHTSTOT,
	NBRMSCGUH_NNGUHTSSUCC AS NNGUHTSSUCC,
	NBRMSCGUH_NNGUHISTOT AS NNGUHISTOT,
	NBRMSCGUH_NNGUHISSUCC AS NNGUHISSUCC,
	NBRMSCGUH_NNGUSCATOT AS NNGUSCATOT,
	NBRMSCGUH_NNGSUSCASUCC AS NNGSUSCASUCC,
	NBRMSCGUH_NNGUREDREJ AS NNGUREDREJ
FROM
    dc.DC_E_CNAXE_MSCOBJ_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

