---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	PAGING_NPAG1LOTOT AS NPAG1LOTOT,
	PAGING_NPAG1GLTOT AS NPAG1GLTOT,
	PAGING_NPAG2LOTOT AS NPAG2LOTOT,
	PAGING_NPAG2GLTOT AS NPAG2GLTOT,
	PAGING_NPAG1RESUCC AS NPAG1RESUCC,
	PAGING_NPAG2RESUCC AS NPAG2RESUCC,
	PAGING_NPAGERR AS NPAGERR,
	PAGING_NPAG1GPRSTOT AS NPAG1GPRSTOT,
	PAGING_NPAG2GPRSTOT AS NPAG2GPRSTOT,
	PAGING_NPAG1GPRSSUCC AS NPAG1GPRSSUCC,
	PAGING_NPAG2GPRSSUCC AS NPAG2GPRSSUCC,
	PAGING_NPAGGPRSFAIL AS NPAGGPRSFAIL,
	PAGING_NMSUNREACHGPRS AS NMSUNREACHGPRS,
	PAGING_NPAGSMSTOT AS NPAGSMSTOT,
	PAGING_NPAGSMSRES AS NPAGSMSRES,
	PAGING_NPAG1LOUTOT AS NPAG1LOUTOT,
	PAGING_NPAG1GLUTOT AS NPAG1GLUTOT,
	PAGING_NPAG2LOUTOT AS NPAG2LOUTOT,
	PAGING_NPAG2GLUTOT AS NPAG2GLUTOT,
	PAGING_NPAG1REUSUCC AS NPAG1REUSUCC,
	PAGING_NPAG2REUSUCC AS NPAG2REUSUCC,
	PAGING_NPAGUERR AS NPAGUERR,
	PAGING_NPAGAREIU AS NPAGAREIU,
	PAGING_NPAGIUREA AS NPAGIUREA,
	PAGING_NSISPTOT AS NSISPTOT,
	PAGING_NSISPSUCC AS NSISPSUCC,
	PAGING_NBISPTOT AS NBISPTOT,
	PAGING_NBISPSUCC AS NBISPSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	PAGING_NPAG1LOTOT AS NPAG1LOTOT,
	PAGING_NPAG1GLTOT AS NPAG1GLTOT,
	PAGING_NPAG2LOTOT AS NPAG2LOTOT,
	PAGING_NPAG2GLTOT AS NPAG2GLTOT,
	PAGING_NPAG1RESUCC AS NPAG1RESUCC,
	PAGING_NPAG2RESUCC AS NPAG2RESUCC,
	PAGING_NPAGERR AS NPAGERR,
	PAGING_NPAG1GPRSTOT AS NPAG1GPRSTOT,
	PAGING_NPAG2GPRSTOT AS NPAG2GPRSTOT,
	PAGING_NPAG1GPRSSUCC AS NPAG1GPRSSUCC,
	PAGING_NPAG2GPRSSUCC AS NPAG2GPRSSUCC,
	PAGING_NPAGGPRSFAIL AS NPAGGPRSFAIL,
	PAGING_NMSUNREACHGPRS AS NMSUNREACHGPRS,
	PAGING_NPAGSMSTOT AS NPAGSMSTOT,
	PAGING_NPAGSMSRES AS NPAGSMSRES,
	PAGING_NPAG1LOUTOT AS NPAG1LOUTOT,
	PAGING_NPAG1GLUTOT AS NPAG1GLUTOT,
	PAGING_NPAG2LOUTOT AS NPAG2LOUTOT,
	PAGING_NPAG2GLUTOT AS NPAG2GLUTOT,
	PAGING_NPAG1REUSUCC AS NPAG1REUSUCC,
	PAGING_NPAG2REUSUCC AS NPAG2REUSUCC,
	PAGING_NPAGUERR AS NPAGUERR,
	PAGING_NPAGAREIU AS NPAGAREIU,
	PAGING_NPAGIUREA AS NPAGIUREA,
	PAGING_NSISPTOT AS NSISPTOT,
	PAGING_NSISPSUCC AS NSISPSUCC,
	PAGING_NBISPTOT AS NBISPTOT,
	PAGING_NBISPSUCC AS NBISPSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	PAGING_NPAG1LOTOT AS NPAG1LOTOT,
	PAGING_NPAG1GLTOT AS NPAG1GLTOT,
	PAGING_NPAG2LOTOT AS NPAG2LOTOT,
	PAGING_NPAG2GLTOT AS NPAG2GLTOT,
	PAGING_NPAG1RESUCC AS NPAG1RESUCC,
	PAGING_NPAG2RESUCC AS NPAG2RESUCC,
	PAGING_NPAGERR AS NPAGERR,
	PAGING_NPAG1GPRSTOT AS NPAG1GPRSTOT,
	PAGING_NPAG2GPRSTOT AS NPAG2GPRSTOT,
	PAGING_NPAG1GPRSSUCC AS NPAG1GPRSSUCC,
	PAGING_NPAG2GPRSSUCC AS NPAG2GPRSSUCC,
	PAGING_NPAGGPRSFAIL AS NPAGGPRSFAIL,
	PAGING_NMSUNREACHGPRS AS NMSUNREACHGPRS,
	PAGING_NPAGSMSTOT AS NPAGSMSTOT,
	PAGING_NPAGSMSRES AS NPAGSMSRES,
	PAGING_NPAG1LOUTOT AS NPAG1LOUTOT,
	PAGING_NPAG1GLUTOT AS NPAG1GLUTOT,
	PAGING_NPAG2LOUTOT AS NPAG2LOUTOT,
	PAGING_NPAG2GLUTOT AS NPAG2GLUTOT,
	PAGING_NPAG1REUSUCC AS NPAG1REUSUCC,
	PAGING_NPAG2REUSUCC AS NPAG2REUSUCC,
	PAGING_NPAGUERR AS NPAGUERR,
	PAGING_NPAGAREIU AS NPAGAREIU,
	PAGING_NPAGIUREA AS NPAGIUREA,
	PAGING_NSISPTOT AS NSISPTOT,
	PAGING_NSISPSUCC AS NSISPSUCC,
	PAGING_NBISPTOT AS NBISPTOT,
	PAGING_NBISPSUCC AS NBISPSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	PAGING_NPAG1LOTOT AS NPAG1LOTOT,
	PAGING_NPAG1GLTOT AS NPAG1GLTOT,
	PAGING_NPAG2LOTOT AS NPAG2LOTOT,
	PAGING_NPAG2GLTOT AS NPAG2GLTOT,
	PAGING_NPAG1RESUCC AS NPAG1RESUCC,
	PAGING_NPAG2RESUCC AS NPAG2RESUCC,
	PAGING_NPAGERR AS NPAGERR,
	PAGING_NPAG1GPRSTOT AS NPAG1GPRSTOT,
	PAGING_NPAG2GPRSTOT AS NPAG2GPRSTOT,
	PAGING_NPAG1GPRSSUCC AS NPAG1GPRSSUCC,
	PAGING_NPAG2GPRSSUCC AS NPAG2GPRSSUCC,
	PAGING_NPAGGPRSFAIL AS NPAGGPRSFAIL,
	PAGING_NMSUNREACHGPRS AS NMSUNREACHGPRS,
	PAGING_NPAGSMSTOT AS NPAGSMSTOT,
	PAGING_NPAGSMSRES AS NPAGSMSRES,
	PAGING_NPAG1LOUTOT AS NPAG1LOUTOT,
	PAGING_NPAG1GLUTOT AS NPAG1GLUTOT,
	PAGING_NPAG2LOUTOT AS NPAG2LOUTOT,
	PAGING_NPAG2GLUTOT AS NPAG2GLUTOT,
	PAGING_NPAG1REUSUCC AS NPAG1REUSUCC,
	PAGING_NPAG2REUSUCC AS NPAG2REUSUCC,
	PAGING_NPAGUERR AS NPAGUERR,
	PAGING_NPAGAREIU AS NPAGAREIU,
	PAGING_NPAGIUREA AS NPAGIUREA,
	PAGING_NSISPTOT AS NSISPTOT,
	PAGING_NSISPSUCC AS NSISPSUCC,
	PAGING_NBISPTOT AS NBISPTOT,
	PAGING_NBISPSUCC AS NBISPSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	PAGING_NPAG1LOTOT AS NPAG1LOTOT,
	PAGING_NPAG1GLTOT AS NPAG1GLTOT,
	PAGING_NPAG2LOTOT AS NPAG2LOTOT,
	PAGING_NPAG2GLTOT AS NPAG2GLTOT,
	PAGING_NPAG1RESUCC AS NPAG1RESUCC,
	PAGING_NPAG2RESUCC AS NPAG2RESUCC,
	PAGING_NPAGERR AS NPAGERR,
	PAGING_NPAG1GPRSTOT AS NPAG1GPRSTOT,
	PAGING_NPAG2GPRSTOT AS NPAG2GPRSTOT,
	PAGING_NPAG1GPRSSUCC AS NPAG1GPRSSUCC,
	PAGING_NPAG2GPRSSUCC AS NPAG2GPRSSUCC,
	PAGING_NPAGGPRSFAIL AS NPAGGPRSFAIL,
	PAGING_NMSUNREACHGPRS AS NMSUNREACHGPRS,
	PAGING_NPAGSMSTOT AS NPAGSMSTOT,
	PAGING_NPAGSMSRES AS NPAGSMSRES,
	PAGING_NPAG1LOUTOT AS NPAG1LOUTOT,
	PAGING_NPAG1GLUTOT AS NPAG1GLUTOT,
	PAGING_NPAG2LOUTOT AS NPAG2LOUTOT,
	PAGING_NPAG2GLUTOT AS NPAG2GLUTOT,
	PAGING_NPAG1REUSUCC AS NPAG1REUSUCC,
	PAGING_NPAG2REUSUCC AS NPAG2REUSUCC,
	PAGING_NPAGUERR AS NPAGUERR,
	PAGING_NPAGAREIU AS NPAGAREIU,
	PAGING_NPAGIUREA AS NPAGIUREA,
	PAGING_NSISPTOT AS NSISPTOT,
	PAGING_NSISPSUCC AS NSISPSUCC,
	PAGING_NBISPTOT AS NBISPTOT,
	PAGING_NBISPSUCC AS NBISPSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	PAGING_NPAG1LOTOT AS NPAG1LOTOT,
	PAGING_NPAG1GLTOT AS NPAG1GLTOT,
	PAGING_NPAG2LOTOT AS NPAG2LOTOT,
	PAGING_NPAG2GLTOT AS NPAG2GLTOT,
	PAGING_NPAG1RESUCC AS NPAG1RESUCC,
	PAGING_NPAG2RESUCC AS NPAG2RESUCC,
	PAGING_NPAGERR AS NPAGERR,
	PAGING_NPAG1GPRSTOT AS NPAG1GPRSTOT,
	PAGING_NPAG2GPRSTOT AS NPAG2GPRSTOT,
	PAGING_NPAG1GPRSSUCC AS NPAG1GPRSSUCC,
	PAGING_NPAG2GPRSSUCC AS NPAG2GPRSSUCC,
	PAGING_NPAGGPRSFAIL AS NPAGGPRSFAIL,
	PAGING_NMSUNREACHGPRS AS NMSUNREACHGPRS,
	PAGING_NPAGSMSTOT AS NPAGSMSTOT,
	PAGING_NPAGSMSRES AS NPAGSMSRES,
	PAGING_NPAG1LOUTOT AS NPAG1LOUTOT,
	PAGING_NPAG1GLUTOT AS NPAG1GLUTOT,
	PAGING_NPAG2LOUTOT AS NPAG2LOUTOT,
	PAGING_NPAG2GLUTOT AS NPAG2GLUTOT,
	PAGING_NPAG1REUSUCC AS NPAG1REUSUCC,
	PAGING_NPAG2REUSUCC AS NPAG2REUSUCC,
	PAGING_NPAGUERR AS NPAGUERR,
	PAGING_NPAGAREIU AS NPAGAREIU,
	PAGING_NPAGIUREA AS NPAGIUREA,
	PAGING_NSISPTOT AS NSISPTOT,
	PAGING_NSISPSUCC AS NSISPSUCC,
	PAGING_NBISPTOT AS NBISPTOT,
	PAGING_NBISPSUCC AS NBISPSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	PAGING_NPAG1LOTOT AS NPAG1LOTOT,
	PAGING_NPAG1GLTOT AS NPAG1GLTOT,
	PAGING_NPAG2LOTOT AS NPAG2LOTOT,
	PAGING_NPAG2GLTOT AS NPAG2GLTOT,
	PAGING_NPAG1RESUCC AS NPAG1RESUCC,
	PAGING_NPAG2RESUCC AS NPAG2RESUCC,
	PAGING_NPAGERR AS NPAGERR,
	PAGING_NPAG1GPRSTOT AS NPAG1GPRSTOT,
	PAGING_NPAG2GPRSTOT AS NPAG2GPRSTOT,
	PAGING_NPAG1GPRSSUCC AS NPAG1GPRSSUCC,
	PAGING_NPAG2GPRSSUCC AS NPAG2GPRSSUCC,
	PAGING_NPAGGPRSFAIL AS NPAGGPRSFAIL,
	PAGING_NMSUNREACHGPRS AS NMSUNREACHGPRS,
	PAGING_NPAGSMSTOT AS NPAGSMSTOT,
	PAGING_NPAGSMSRES AS NPAGSMSRES,
	PAGING_NPAG1LOUTOT AS NPAG1LOUTOT,
	PAGING_NPAG1GLUTOT AS NPAG1GLUTOT,
	PAGING_NPAG2LOUTOT AS NPAG2LOUTOT,
	PAGING_NPAG2GLUTOT AS NPAG2GLUTOT,
	PAGING_NPAG1REUSUCC AS NPAG1REUSUCC,
	PAGING_NPAG2REUSUCC AS NPAG2REUSUCC,
	PAGING_NPAGUERR AS NPAGUERR,
	PAGING_NPAGAREIU AS NPAGAREIU,
	PAGING_NPAGIUREA AS NPAGIUREA,
	PAGING_NSISPTOT AS NSISPTOT,
	PAGING_NSISPSUCC AS NSISPSUCC,
	PAGING_NBISPTOT AS NBISPTOT,
	PAGING_NBISPSUCC AS NBISPSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

