---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBSTSSMTOT,
	NRNTRRRTOT,
	NRNTSRRTOT,
	NRNTIHRSUCC,
	NRNTOHRSUCC,
	NRNTRRRGTOT,
	NRNTORGSUCC,
	NRNFRMSCCI,
	NRNFRMTOTI,
	NRNTOMSCCO,
	NRNTOMTOTO,
	NRNFRRRTOT,
	NRNTORRTOT,
	NRNTSRRUTOT,
	NRNTIHRUSUCC,
	NRNTLRCTOT,
	NRNTLRSUCC,
	NRNTRRCTOT,
	NRNTLRDRTOT,
	NRNTLRDSUCC,
	NRFRMAMR,
	NRFRM2AMR,
	0 AS NRFRMWBAMR,
	NRTOAMR,
	NRTO2AMR,
	NRTOWBAMR
FROM
    dc.DC_E_CNAXE_RNCSTAT_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBSTSSMTOT,
	NRNTRRRTOT,
	NRNTSRRTOT,
	NRNTIHRSUCC,
	NRNTOHRSUCC,
	NRNTRRRGTOT,
	NRNTORGSUCC,
	NRNFRMSCCI,
	NRNFRMTOTI,
	NRNTOMSCCO,
	NRNTOMTOTO,
	NRNFRRRTOT,
	NRNTORRTOT,
	NRNTSRRUTOT,
	NRNTIHRUSUCC,
	NRNTLRCTOT,
	NRNTLRSUCC,
	NRNTRRCTOT,
	NRNTLRDRTOT,
	NRNTLRDSUCC,
	NRFRMAMR,
	NRFRM2AMR,
	0 AS NRFRMWBAMR,
	NRTOAMR,
	NRTO2AMR,
	NRTOWBAMR
FROM
    dc.DC_E_CNAXE_RNCSTAT_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBSTSSMTOT,
	NRNTRRRTOT,
	NRNTSRRTOT,
	NRNTIHRSUCC,
	NRNTOHRSUCC,
	NRNTRRRGTOT,
	NRNTORGSUCC,
	NRNFRMSCCI,
	NRNFRMTOTI,
	NRNTOMSCCO,
	NRNTOMTOTO,
	NRNFRRRTOT,
	NRNTORRTOT,
	NRNTSRRUTOT,
	NRNTIHRUSUCC,
	NRNTLRCTOT,
	NRNTLRSUCC,
	NRNTRRCTOT,
	NRNTLRDRTOT,
	NRNTLRDSUCC,
	NRFRMAMR,
	NRFRM2AMR,
	0 AS NRFRMWBAMR,
	NRTOAMR,
	NRTO2AMR,
	NRTOWBAMR
FROM
    dc.DC_E_CNAXE_RNCSTAT_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBSTSSMTOT,
	NRNTRRRTOT,
	NRNTSRRTOT,
	NRNTIHRSUCC,
	NRNTOHRSUCC,
	NRNTRRRGTOT,
	NRNTORGSUCC,
	NRNFRMSCCI,
	NRNFRMTOTI,
	NRNTOMSCCO,
	NRNTOMTOTO,
	NRNFRRRTOT,
	NRNTORRTOT,
	NRNTSRRUTOT,
	NRNTIHRUSUCC,
	NRNTLRCTOT,
	NRNTLRSUCC,
	NRNTRRCTOT,
	NRNTLRDRTOT,
	NRNTLRDSUCC,
	NRFRMAMR,
	NRFRM2AMR,
	0 AS NRFRMWBAMR,
	NRTOAMR,
	NRTO2AMR,
	NRTOWBAMR
FROM
    dc.DC_E_CNAXE_RNCSTAT_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBSTSSMTOT,
	NRNTRRRTOT,
	NRNTSRRTOT,
	NRNTIHRSUCC,
	NRNTOHRSUCC,
	NRNTRRRGTOT,
	NRNTORGSUCC,
	NRNFRMSCCI,
	NRNFRMTOTI,
	NRNTOMSCCO,
	NRNTOMTOTO,
	NRNFRRRTOT,
	NRNTORRTOT,
	NRNTSRRUTOT,
	NRNTIHRUSUCC,
	NRNTLRCTOT,
	NRNTLRSUCC,
	NRNTRRCTOT,
	NRNTLRDRTOT,
	NRNTLRDSUCC,
	NRFRMAMR,
	NRFRM2AMR,
	0 AS NRFRMWBAMR,
	NRTOAMR,
	NRTO2AMR,
	NRTOWBAMR
FROM
    dc.DC_E_CNAXE_RNCSTAT_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBSTSSMTOT,
	NRNTRRRTOT,
	NRNTSRRTOT,
	NRNTIHRSUCC,
	NRNTOHRSUCC,
	NRNTRRRGTOT,
	NRNTORGSUCC,
	NRNFRMSCCI,
	NRNFRMTOTI,
	NRNTOMSCCO,
	NRNTOMTOTO,
	NRNFRRRTOT,
	NRNTORRTOT,
	NRNTSRRUTOT,
	NRNTIHRUSUCC,
	NRNTLRCTOT,
	NRNTLRSUCC,
	NRNTRRCTOT,
	NRNTLRDRTOT,
	NRNTLRDSUCC,
	NRFRMAMR,
	NRFRM2AMR,
	0 AS NRFRMWBAMR,
	NRTOAMR,
	NRTO2AMR,
	NRTOWBAMR
FROM
    dc.DC_E_CNAXE_RNCSTAT_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	NBSTSSMTOT,
	NRNTRRRTOT,
	NRNTSRRTOT,
	NRNTIHRSUCC,
	NRNTOHRSUCC,
	NRNTRRRGTOT,
	NRNTORGSUCC,
	NRNFRMSCCI,
	NRNFRMTOTI,
	NRNTOMSCCO,
	NRNTOMTOTO,
	NRNFRRRTOT,
	NRNTORRTOT,
	NRNTSRRUTOT,
	NRNTIHRUSUCC,
	NRNTLRCTOT,
	NRNTLRSUCC,
	NRNTRRCTOT,
	NRNTLRDRTOT,
	NRNTLRDSUCC,
	NRFRMAMR,
	NRFRM2AMR,
	0 AS NRFRMWBAMR,
	NRTOAMR,
	NRTO2AMR,
	NRTOWBAMR
FROM
    dc.DC_E_CNAXE_RNCSTAT_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

