---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SECHAND_NAUTFTCTOT AS NAUTFTCTOT,
	SECHAND_NAUTFTCSUCC AS NAUTFTCSUCC,
	SECHAND_NAUTREQTOT AS NAUTREQTOT,
	SECHAND_NAUTREQSUCC AS NAUTREQSUCC,
	SECHAND_NAUTSREERR AS NAUTSREERR,
	SECHAND_NAUTUSETOT AS NAUTUSETOT,
	SECHAND_NCIPATTTOT AS NCIPATTTOT,
	SECHAND_NCIPSETSUCC AS NCIPSETSUCC,
	SECHAND_NAUTTMSITOT AS NAUTTMSITOT,
	SECHAND_NAUTTMSIERR AS NAUTTMSIERR,
	SECHAND_NAUTTMSISUCC AS NAUTTMSISUCC,
	SECHAND_NAUTREATOT AS NAUTREATOT,
	SECHAND_NAUTREAFLT AS NAUTREAFLT,
	SECHAND_NAUTPPREQ AS NAUTPPREQ,
	SECHAND_NAUTPPREJ AS NAUTPPREJ,
	SECHAND_NAUTPPREP AS NAUTPPREP,
	SECHAND_NCIPHREQ AS NCIPHREQ,
	SECHAND_NCIPHREJ AS NCIPHREJ,
	SECHAND_NAUTMACFAIL AS NAUTMACFAIL,
	SECHAND_NAUTRESYNCH AS NAUTRESYNCH
FROM
    dc.DC_E_CNAXE_MSC_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SECHAND_NAUTFTCTOT AS NAUTFTCTOT,
	SECHAND_NAUTFTCSUCC AS NAUTFTCSUCC,
	SECHAND_NAUTREQTOT AS NAUTREQTOT,
	SECHAND_NAUTREQSUCC AS NAUTREQSUCC,
	SECHAND_NAUTSREERR AS NAUTSREERR,
	SECHAND_NAUTUSETOT AS NAUTUSETOT,
	SECHAND_NCIPATTTOT AS NCIPATTTOT,
	SECHAND_NCIPSETSUCC AS NCIPSETSUCC,
	SECHAND_NAUTTMSITOT AS NAUTTMSITOT,
	SECHAND_NAUTTMSIERR AS NAUTTMSIERR,
	SECHAND_NAUTTMSISUCC AS NAUTTMSISUCC,
	SECHAND_NAUTREATOT AS NAUTREATOT,
	SECHAND_NAUTREAFLT AS NAUTREAFLT,
	SECHAND_NAUTPPREQ AS NAUTPPREQ,
	SECHAND_NAUTPPREJ AS NAUTPPREJ,
	SECHAND_NAUTPPREP AS NAUTPPREP,
	SECHAND_NCIPHREQ AS NCIPHREQ,
	SECHAND_NCIPHREJ AS NCIPHREJ,
	SECHAND_NAUTMACFAIL AS NAUTMACFAIL,
	SECHAND_NAUTRESYNCH AS NAUTRESYNCH
FROM
    dc.DC_E_CNAXE_MSC_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SECHAND_NAUTFTCTOT AS NAUTFTCTOT,
	SECHAND_NAUTFTCSUCC AS NAUTFTCSUCC,
	SECHAND_NAUTREQTOT AS NAUTREQTOT,
	SECHAND_NAUTREQSUCC AS NAUTREQSUCC,
	SECHAND_NAUTSREERR AS NAUTSREERR,
	SECHAND_NAUTUSETOT AS NAUTUSETOT,
	SECHAND_NCIPATTTOT AS NCIPATTTOT,
	SECHAND_NCIPSETSUCC AS NCIPSETSUCC,
	SECHAND_NAUTTMSITOT AS NAUTTMSITOT,
	SECHAND_NAUTTMSIERR AS NAUTTMSIERR,
	SECHAND_NAUTTMSISUCC AS NAUTTMSISUCC,
	SECHAND_NAUTREATOT AS NAUTREATOT,
	SECHAND_NAUTREAFLT AS NAUTREAFLT,
	SECHAND_NAUTPPREQ AS NAUTPPREQ,
	SECHAND_NAUTPPREJ AS NAUTPPREJ,
	SECHAND_NAUTPPREP AS NAUTPPREP,
	SECHAND_NCIPHREQ AS NCIPHREQ,
	SECHAND_NCIPHREJ AS NCIPHREJ,
	SECHAND_NAUTMACFAIL AS NAUTMACFAIL,
	SECHAND_NAUTRESYNCH AS NAUTRESYNCH
FROM
    dc.DC_E_CNAXE_MSC_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SECHAND_NAUTFTCTOT AS NAUTFTCTOT,
	SECHAND_NAUTFTCSUCC AS NAUTFTCSUCC,
	SECHAND_NAUTREQTOT AS NAUTREQTOT,
	SECHAND_NAUTREQSUCC AS NAUTREQSUCC,
	SECHAND_NAUTSREERR AS NAUTSREERR,
	SECHAND_NAUTUSETOT AS NAUTUSETOT,
	SECHAND_NCIPATTTOT AS NCIPATTTOT,
	SECHAND_NCIPSETSUCC AS NCIPSETSUCC,
	SECHAND_NAUTTMSITOT AS NAUTTMSITOT,
	SECHAND_NAUTTMSIERR AS NAUTTMSIERR,
	SECHAND_NAUTTMSISUCC AS NAUTTMSISUCC,
	SECHAND_NAUTREATOT AS NAUTREATOT,
	SECHAND_NAUTREAFLT AS NAUTREAFLT,
	SECHAND_NAUTPPREQ AS NAUTPPREQ,
	SECHAND_NAUTPPREJ AS NAUTPPREJ,
	SECHAND_NAUTPPREP AS NAUTPPREP,
	SECHAND_NCIPHREQ AS NCIPHREQ,
	SECHAND_NCIPHREJ AS NCIPHREJ,
	SECHAND_NAUTMACFAIL AS NAUTMACFAIL,
	SECHAND_NAUTRESYNCH AS NAUTRESYNCH
FROM
    dc.DC_E_CNAXE_MSC_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SECHAND_NAUTFTCTOT AS NAUTFTCTOT,
	SECHAND_NAUTFTCSUCC AS NAUTFTCSUCC,
	SECHAND_NAUTREQTOT AS NAUTREQTOT,
	SECHAND_NAUTREQSUCC AS NAUTREQSUCC,
	SECHAND_NAUTSREERR AS NAUTSREERR,
	SECHAND_NAUTUSETOT AS NAUTUSETOT,
	SECHAND_NCIPATTTOT AS NCIPATTTOT,
	SECHAND_NCIPSETSUCC AS NCIPSETSUCC,
	SECHAND_NAUTTMSITOT AS NAUTTMSITOT,
	SECHAND_NAUTTMSIERR AS NAUTTMSIERR,
	SECHAND_NAUTTMSISUCC AS NAUTTMSISUCC,
	SECHAND_NAUTREATOT AS NAUTREATOT,
	SECHAND_NAUTREAFLT AS NAUTREAFLT,
	SECHAND_NAUTPPREQ AS NAUTPPREQ,
	SECHAND_NAUTPPREJ AS NAUTPPREJ,
	SECHAND_NAUTPPREP AS NAUTPPREP,
	SECHAND_NCIPHREQ AS NCIPHREQ,
	SECHAND_NCIPHREJ AS NCIPHREJ,
	SECHAND_NAUTMACFAIL AS NAUTMACFAIL,
	SECHAND_NAUTRESYNCH AS NAUTRESYNCH
FROM
    dc.DC_E_CNAXE_MSC_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SECHAND_NAUTFTCTOT AS NAUTFTCTOT,
	SECHAND_NAUTFTCSUCC AS NAUTFTCSUCC,
	SECHAND_NAUTREQTOT AS NAUTREQTOT,
	SECHAND_NAUTREQSUCC AS NAUTREQSUCC,
	SECHAND_NAUTSREERR AS NAUTSREERR,
	SECHAND_NAUTUSETOT AS NAUTUSETOT,
	SECHAND_NCIPATTTOT AS NCIPATTTOT,
	SECHAND_NCIPSETSUCC AS NCIPSETSUCC,
	SECHAND_NAUTTMSITOT AS NAUTTMSITOT,
	SECHAND_NAUTTMSIERR AS NAUTTMSIERR,
	SECHAND_NAUTTMSISUCC AS NAUTTMSISUCC,
	SECHAND_NAUTREATOT AS NAUTREATOT,
	SECHAND_NAUTREAFLT AS NAUTREAFLT,
	SECHAND_NAUTPPREQ AS NAUTPPREQ,
	SECHAND_NAUTPPREJ AS NAUTPPREJ,
	SECHAND_NAUTPPREP AS NAUTPPREP,
	SECHAND_NCIPHREQ AS NCIPHREQ,
	SECHAND_NCIPHREJ AS NCIPHREJ,
	SECHAND_NAUTMACFAIL AS NAUTMACFAIL,
	SECHAND_NAUTRESYNCH AS NAUTRESYNCH
FROM
    dc.DC_E_CNAXE_MSC_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SECHAND_NAUTFTCTOT AS NAUTFTCTOT,
	SECHAND_NAUTFTCSUCC AS NAUTFTCSUCC,
	SECHAND_NAUTREQTOT AS NAUTREQTOT,
	SECHAND_NAUTREQSUCC AS NAUTREQSUCC,
	SECHAND_NAUTSREERR AS NAUTSREERR,
	SECHAND_NAUTUSETOT AS NAUTUSETOT,
	SECHAND_NCIPATTTOT AS NCIPATTTOT,
	SECHAND_NCIPSETSUCC AS NCIPSETSUCC,
	SECHAND_NAUTTMSITOT AS NAUTTMSITOT,
	SECHAND_NAUTTMSIERR AS NAUTTMSIERR,
	SECHAND_NAUTTMSISUCC AS NAUTTMSISUCC,
	SECHAND_NAUTREATOT AS NAUTREATOT,
	SECHAND_NAUTREAFLT AS NAUTREAFLT,
	SECHAND_NAUTPPREQ AS NAUTPPREQ,
	SECHAND_NAUTPPREJ AS NAUTPPREJ,
	SECHAND_NAUTPPREP AS NAUTPPREP,
	SECHAND_NCIPHREQ AS NCIPHREQ,
	SECHAND_NCIPHREJ AS NCIPHREJ,
	SECHAND_NAUTMACFAIL AS NAUTMACFAIL,
	SECHAND_NAUTRESYNCH AS NAUTRESYNCH
FROM
    dc.DC_E_CNAXE_MSC_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

