---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SHAM_SRFATT AS SRFATT,
	SHAM_SRFCNG AS SRFCNG,
	SHAM_TIMESRF AS TIMESRF,
	SHAM_SRFTRF AS SRFTRF,
	SHAM_ETCATT AS ETCATT,
	SHAM_ETCCNG AS ETCCNG,
	SHAM_TIMEETC AS TIMEETC,
	SHAM_ETCTRF AS ETCTRF,
	SHAM_CGREQ AS CGREQ,
	SHAM_CLREQ AS CLREQ,
	SHAM_SFREQ AS SFREQ,
	SHAM_CDIALATTFAIL AS CDIALATTFAIL,
	SHAM_CSENDREQREJ AS CSENDREQREJ,
	SHAM_CDIALINITATT AS CDIALINITATT,
	SHAM_CDIALINITCONG AS CDIALINITCONG,
	SHAM_CDIALABORTSSF AS CDIALABORTSSF,
	SHAM_CDIALINPROG AS CDIALINPROG,
	SHAM_CDIALPROCESSED AS CDIALPROCESSED,
	SHAM_CDIALREJTCAP AS CDIALREJTCAP,
	SHAM_CDIALREMABORT AS CDIALREMABORT,
	SHAM_CDIALSCFERRREJ AS CDIALSCFERRREJ,
	SHAM_CERRREJSEND AS CERRREJSEND,
	SHAM_DIAATT AS DIAATT,
	SHAM_DIACNG AS DIACNG,
	SHAM_DIATRF AS DIATRF,
	SHAM_CALLATT AS CALLATT,
	SHAM_CALLTRF AS CALLTRF,
	SHAM_CALLCNG AS CALLCNG,
	SHAM_NSMSINV AS NSMSINV,
	SHAM_NSMSFAIL AS NSMSFAIL
FROM
    dc.DC_E_CNAXE_TSC_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SHAM_SRFATT AS SRFATT,
	SHAM_SRFCNG AS SRFCNG,
	SHAM_TIMESRF AS TIMESRF,
	SHAM_SRFTRF AS SRFTRF,
	SHAM_ETCATT AS ETCATT,
	SHAM_ETCCNG AS ETCCNG,
	SHAM_TIMEETC AS TIMEETC,
	SHAM_ETCTRF AS ETCTRF,
	SHAM_CGREQ AS CGREQ,
	SHAM_CLREQ AS CLREQ,
	SHAM_SFREQ AS SFREQ,
	SHAM_CDIALATTFAIL AS CDIALATTFAIL,
	SHAM_CSENDREQREJ AS CSENDREQREJ,
	SHAM_CDIALINITATT AS CDIALINITATT,
	SHAM_CDIALINITCONG AS CDIALINITCONG,
	SHAM_CDIALABORTSSF AS CDIALABORTSSF,
	SHAM_CDIALINPROG AS CDIALINPROG,
	SHAM_CDIALPROCESSED AS CDIALPROCESSED,
	SHAM_CDIALREJTCAP AS CDIALREJTCAP,
	SHAM_CDIALREMABORT AS CDIALREMABORT,
	SHAM_CDIALSCFERRREJ AS CDIALSCFERRREJ,
	SHAM_CERRREJSEND AS CERRREJSEND,
	SHAM_DIAATT AS DIAATT,
	SHAM_DIACNG AS DIACNG,
	SHAM_DIATRF AS DIATRF,
	SHAM_CALLATT AS CALLATT,
	SHAM_CALLTRF AS CALLTRF,
	SHAM_CALLCNG AS CALLCNG,
	SHAM_NSMSINV AS NSMSINV,
	SHAM_NSMSFAIL AS NSMSFAIL
FROM
    dc.DC_E_CNAXE_TSC_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SHAM_SRFATT AS SRFATT,
	SHAM_SRFCNG AS SRFCNG,
	SHAM_TIMESRF AS TIMESRF,
	SHAM_SRFTRF AS SRFTRF,
	SHAM_ETCATT AS ETCATT,
	SHAM_ETCCNG AS ETCCNG,
	SHAM_TIMEETC AS TIMEETC,
	SHAM_ETCTRF AS ETCTRF,
	SHAM_CGREQ AS CGREQ,
	SHAM_CLREQ AS CLREQ,
	SHAM_SFREQ AS SFREQ,
	SHAM_CDIALATTFAIL AS CDIALATTFAIL,
	SHAM_CSENDREQREJ AS CSENDREQREJ,
	SHAM_CDIALINITATT AS CDIALINITATT,
	SHAM_CDIALINITCONG AS CDIALINITCONG,
	SHAM_CDIALABORTSSF AS CDIALABORTSSF,
	SHAM_CDIALINPROG AS CDIALINPROG,
	SHAM_CDIALPROCESSED AS CDIALPROCESSED,
	SHAM_CDIALREJTCAP AS CDIALREJTCAP,
	SHAM_CDIALREMABORT AS CDIALREMABORT,
	SHAM_CDIALSCFERRREJ AS CDIALSCFERRREJ,
	SHAM_CERRREJSEND AS CERRREJSEND,
	SHAM_DIAATT AS DIAATT,
	SHAM_DIACNG AS DIACNG,
	SHAM_DIATRF AS DIATRF,
	SHAM_CALLATT AS CALLATT,
	SHAM_CALLTRF AS CALLTRF,
	SHAM_CALLCNG AS CALLCNG,
	SHAM_NSMSINV AS NSMSINV,
	SHAM_NSMSFAIL AS NSMSFAIL
FROM
    dc.DC_E_CNAXE_TSC_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SHAM_SRFATT AS SRFATT,
	SHAM_SRFCNG AS SRFCNG,
	SHAM_TIMESRF AS TIMESRF,
	SHAM_SRFTRF AS SRFTRF,
	SHAM_ETCATT AS ETCATT,
	SHAM_ETCCNG AS ETCCNG,
	SHAM_TIMEETC AS TIMEETC,
	SHAM_ETCTRF AS ETCTRF,
	SHAM_CGREQ AS CGREQ,
	SHAM_CLREQ AS CLREQ,
	SHAM_SFREQ AS SFREQ,
	SHAM_CDIALATTFAIL AS CDIALATTFAIL,
	SHAM_CSENDREQREJ AS CSENDREQREJ,
	SHAM_CDIALINITATT AS CDIALINITATT,
	SHAM_CDIALINITCONG AS CDIALINITCONG,
	SHAM_CDIALABORTSSF AS CDIALABORTSSF,
	SHAM_CDIALINPROG AS CDIALINPROG,
	SHAM_CDIALPROCESSED AS CDIALPROCESSED,
	SHAM_CDIALREJTCAP AS CDIALREJTCAP,
	SHAM_CDIALREMABORT AS CDIALREMABORT,
	SHAM_CDIALSCFERRREJ AS CDIALSCFERRREJ,
	SHAM_CERRREJSEND AS CERRREJSEND,
	SHAM_DIAATT AS DIAATT,
	SHAM_DIACNG AS DIACNG,
	SHAM_DIATRF AS DIATRF,
	SHAM_CALLATT AS CALLATT,
	SHAM_CALLTRF AS CALLTRF,
	SHAM_CALLCNG AS CALLCNG,
	SHAM_NSMSINV AS NSMSINV,
	SHAM_NSMSFAIL AS NSMSFAIL
FROM
    dc.DC_E_CNAXE_TSC_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SHAM_SRFATT AS SRFATT,
	SHAM_SRFCNG AS SRFCNG,
	SHAM_TIMESRF AS TIMESRF,
	SHAM_SRFTRF AS SRFTRF,
	SHAM_ETCATT AS ETCATT,
	SHAM_ETCCNG AS ETCCNG,
	SHAM_TIMEETC AS TIMEETC,
	SHAM_ETCTRF AS ETCTRF,
	SHAM_CGREQ AS CGREQ,
	SHAM_CLREQ AS CLREQ,
	SHAM_SFREQ AS SFREQ,
	SHAM_CDIALATTFAIL AS CDIALATTFAIL,
	SHAM_CSENDREQREJ AS CSENDREQREJ,
	SHAM_CDIALINITATT AS CDIALINITATT,
	SHAM_CDIALINITCONG AS CDIALINITCONG,
	SHAM_CDIALABORTSSF AS CDIALABORTSSF,
	SHAM_CDIALINPROG AS CDIALINPROG,
	SHAM_CDIALPROCESSED AS CDIALPROCESSED,
	SHAM_CDIALREJTCAP AS CDIALREJTCAP,
	SHAM_CDIALREMABORT AS CDIALREMABORT,
	SHAM_CDIALSCFERRREJ AS CDIALSCFERRREJ,
	SHAM_CERRREJSEND AS CERRREJSEND,
	SHAM_DIAATT AS DIAATT,
	SHAM_DIACNG AS DIACNG,
	SHAM_DIATRF AS DIATRF,
	SHAM_CALLATT AS CALLATT,
	SHAM_CALLTRF AS CALLTRF,
	SHAM_CALLCNG AS CALLCNG,
	SHAM_NSMSINV AS NSMSINV,
	SHAM_NSMSFAIL AS NSMSFAIL
FROM
    dc.DC_E_CNAXE_TSC_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SHAM_SRFATT AS SRFATT,
	SHAM_SRFCNG AS SRFCNG,
	SHAM_TIMESRF AS TIMESRF,
	SHAM_SRFTRF AS SRFTRF,
	SHAM_ETCATT AS ETCATT,
	SHAM_ETCCNG AS ETCCNG,
	SHAM_TIMEETC AS TIMEETC,
	SHAM_ETCTRF AS ETCTRF,
	SHAM_CGREQ AS CGREQ,
	SHAM_CLREQ AS CLREQ,
	SHAM_SFREQ AS SFREQ,
	SHAM_CDIALATTFAIL AS CDIALATTFAIL,
	SHAM_CSENDREQREJ AS CSENDREQREJ,
	SHAM_CDIALINITATT AS CDIALINITATT,
	SHAM_CDIALINITCONG AS CDIALINITCONG,
	SHAM_CDIALABORTSSF AS CDIALABORTSSF,
	SHAM_CDIALINPROG AS CDIALINPROG,
	SHAM_CDIALPROCESSED AS CDIALPROCESSED,
	SHAM_CDIALREJTCAP AS CDIALREJTCAP,
	SHAM_CDIALREMABORT AS CDIALREMABORT,
	SHAM_CDIALSCFERRREJ AS CDIALSCFERRREJ,
	SHAM_CERRREJSEND AS CERRREJSEND,
	SHAM_DIAATT AS DIAATT,
	SHAM_DIACNG AS DIACNG,
	SHAM_DIATRF AS DIATRF,
	SHAM_CALLATT AS CALLATT,
	SHAM_CALLTRF AS CALLTRF,
	SHAM_CALLCNG AS CALLCNG,
	SHAM_NSMSINV AS NSMSINV,
	SHAM_NSMSFAIL AS NSMSFAIL
FROM
    dc.DC_E_CNAXE_TSC_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	SHAM_SRFATT AS SRFATT,
	SHAM_SRFCNG AS SRFCNG,
	SHAM_TIMESRF AS TIMESRF,
	SHAM_SRFTRF AS SRFTRF,
	SHAM_ETCATT AS ETCATT,
	SHAM_ETCCNG AS ETCCNG,
	SHAM_TIMEETC AS TIMEETC,
	SHAM_ETCTRF AS ETCTRF,
	SHAM_CGREQ AS CGREQ,
	SHAM_CLREQ AS CLREQ,
	SHAM_SFREQ AS SFREQ,
	SHAM_CDIALATTFAIL AS CDIALATTFAIL,
	SHAM_CSENDREQREJ AS CSENDREQREJ,
	SHAM_CDIALINITATT AS CDIALINITATT,
	SHAM_CDIALINITCONG AS CDIALINITCONG,
	SHAM_CDIALABORTSSF AS CDIALABORTSSF,
	SHAM_CDIALINPROG AS CDIALINPROG,
	SHAM_CDIALPROCESSED AS CDIALPROCESSED,
	SHAM_CDIALREJTCAP AS CDIALREJTCAP,
	SHAM_CDIALREMABORT AS CDIALREMABORT,
	SHAM_CDIALSCFERRREJ AS CDIALSCFERRREJ,
	SHAM_CERRREJSEND AS CERRREJSEND,
	SHAM_DIAATT AS DIAATT,
	SHAM_DIACNG AS DIACNG,
	SHAM_DIATRF AS DIATRF,
	SHAM_CALLATT AS CALLATT,
	SHAM_CALLTRF AS CALLTRF,
	SHAM_CALLCNG AS CALLCNG,
	SHAM_NSMSINV AS NSMSINV,
	SHAM_NSMSFAIL AS NSMSFAIL
FROM
    dc.DC_E_CNAXE_TSC_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

