---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UGHNDOVER_NUGHNDRRQDTOT AS NUGHNDRRQDTOT,
	UGHNDOVER_NUGHNDREQTOT AS NUGHNDREQTOT,
	UGHNDOVER_NUGHNDREQSUCC AS NUGHNDREQSUCC,
	UGHNDOVER_NUGHNDCMDTOT AS NUGHNDCMDTOT,
	UGHNDOVER_NUGHNDDGSSUCC AS NUGHNDDGSSUCC,
	UGHNDOVER_NUGHNDCGSSUCC AS NUGHNDCGSSUCC,
	UGHNDOVER_NUGHNDATTSUCC AS NUGHNDATTSUCC,
	UGHNDOVER_NUGHNDRELERR AS NUGHNDRELERR,
	UGHNDOVER_NUGHRNCBSCTOT AS NUGHRNCBSCTOT,
	UGHNDOVER_NUGHRNCBSCSUCC AS NUGHRNCBSCSUCC,
	UGHNDOVER_NUGHNDSDTOT AS NUGHNDSDTOT,
	UGHNDOVER_NUGHNDSDSUCC AS NUGHNDSDSUCC,
	UGHNDOVER_NUGHNDSTTOT AS NUGHNDSTTOT,
	UGHNDOVER_NUGHNDSTSUCC AS NUGHNDSTSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UGHNDOVER_NUGHNDRRQDTOT AS NUGHNDRRQDTOT,
	UGHNDOVER_NUGHNDREQTOT AS NUGHNDREQTOT,
	UGHNDOVER_NUGHNDREQSUCC AS NUGHNDREQSUCC,
	UGHNDOVER_NUGHNDCMDTOT AS NUGHNDCMDTOT,
	UGHNDOVER_NUGHNDDGSSUCC AS NUGHNDDGSSUCC,
	UGHNDOVER_NUGHNDCGSSUCC AS NUGHNDCGSSUCC,
	UGHNDOVER_NUGHNDATTSUCC AS NUGHNDATTSUCC,
	UGHNDOVER_NUGHNDRELERR AS NUGHNDRELERR,
	UGHNDOVER_NUGHRNCBSCTOT AS NUGHRNCBSCTOT,
	UGHNDOVER_NUGHRNCBSCSUCC AS NUGHRNCBSCSUCC,
	UGHNDOVER_NUGHNDSDTOT AS NUGHNDSDTOT,
	UGHNDOVER_NUGHNDSDSUCC AS NUGHNDSDSUCC,
	UGHNDOVER_NUGHNDSTTOT AS NUGHNDSTTOT,
	UGHNDOVER_NUGHNDSTSUCC AS NUGHNDSTSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UGHNDOVER_NUGHNDRRQDTOT AS NUGHNDRRQDTOT,
	UGHNDOVER_NUGHNDREQTOT AS NUGHNDREQTOT,
	UGHNDOVER_NUGHNDREQSUCC AS NUGHNDREQSUCC,
	UGHNDOVER_NUGHNDCMDTOT AS NUGHNDCMDTOT,
	UGHNDOVER_NUGHNDDGSSUCC AS NUGHNDDGSSUCC,
	UGHNDOVER_NUGHNDCGSSUCC AS NUGHNDCGSSUCC,
	UGHNDOVER_NUGHNDATTSUCC AS NUGHNDATTSUCC,
	UGHNDOVER_NUGHNDRELERR AS NUGHNDRELERR,
	UGHNDOVER_NUGHRNCBSCTOT AS NUGHRNCBSCTOT,
	UGHNDOVER_NUGHRNCBSCSUCC AS NUGHRNCBSCSUCC,
	UGHNDOVER_NUGHNDSDTOT AS NUGHNDSDTOT,
	UGHNDOVER_NUGHNDSDSUCC AS NUGHNDSDSUCC,
	UGHNDOVER_NUGHNDSTTOT AS NUGHNDSTTOT,
	UGHNDOVER_NUGHNDSTSUCC AS NUGHNDSTSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UGHNDOVER_NUGHNDRRQDTOT AS NUGHNDRRQDTOT,
	UGHNDOVER_NUGHNDREQTOT AS NUGHNDREQTOT,
	UGHNDOVER_NUGHNDREQSUCC AS NUGHNDREQSUCC,
	UGHNDOVER_NUGHNDCMDTOT AS NUGHNDCMDTOT,
	UGHNDOVER_NUGHNDDGSSUCC AS NUGHNDDGSSUCC,
	UGHNDOVER_NUGHNDCGSSUCC AS NUGHNDCGSSUCC,
	UGHNDOVER_NUGHNDATTSUCC AS NUGHNDATTSUCC,
	UGHNDOVER_NUGHNDRELERR AS NUGHNDRELERR,
	UGHNDOVER_NUGHRNCBSCTOT AS NUGHRNCBSCTOT,
	UGHNDOVER_NUGHRNCBSCSUCC AS NUGHRNCBSCSUCC,
	UGHNDOVER_NUGHNDSDTOT AS NUGHNDSDTOT,
	UGHNDOVER_NUGHNDSDSUCC AS NUGHNDSDSUCC,
	UGHNDOVER_NUGHNDSTTOT AS NUGHNDSTTOT,
	UGHNDOVER_NUGHNDSTSUCC AS NUGHNDSTSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UGHNDOVER_NUGHNDRRQDTOT AS NUGHNDRRQDTOT,
	UGHNDOVER_NUGHNDREQTOT AS NUGHNDREQTOT,
	UGHNDOVER_NUGHNDREQSUCC AS NUGHNDREQSUCC,
	UGHNDOVER_NUGHNDCMDTOT AS NUGHNDCMDTOT,
	UGHNDOVER_NUGHNDDGSSUCC AS NUGHNDDGSSUCC,
	UGHNDOVER_NUGHNDCGSSUCC AS NUGHNDCGSSUCC,
	UGHNDOVER_NUGHNDATTSUCC AS NUGHNDATTSUCC,
	UGHNDOVER_NUGHNDRELERR AS NUGHNDRELERR,
	UGHNDOVER_NUGHRNCBSCTOT AS NUGHRNCBSCTOT,
	UGHNDOVER_NUGHRNCBSCSUCC AS NUGHRNCBSCSUCC,
	UGHNDOVER_NUGHNDSDTOT AS NUGHNDSDTOT,
	UGHNDOVER_NUGHNDSDSUCC AS NUGHNDSDSUCC,
	UGHNDOVER_NUGHNDSTTOT AS NUGHNDSTTOT,
	UGHNDOVER_NUGHNDSTSUCC AS NUGHNDSTSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UGHNDOVER_NUGHNDRRQDTOT AS NUGHNDRRQDTOT,
	UGHNDOVER_NUGHNDREQTOT AS NUGHNDREQTOT,
	UGHNDOVER_NUGHNDREQSUCC AS NUGHNDREQSUCC,
	UGHNDOVER_NUGHNDCMDTOT AS NUGHNDCMDTOT,
	UGHNDOVER_NUGHNDDGSSUCC AS NUGHNDDGSSUCC,
	UGHNDOVER_NUGHNDCGSSUCC AS NUGHNDCGSSUCC,
	UGHNDOVER_NUGHNDATTSUCC AS NUGHNDATTSUCC,
	UGHNDOVER_NUGHNDRELERR AS NUGHNDRELERR,
	UGHNDOVER_NUGHRNCBSCTOT AS NUGHRNCBSCTOT,
	UGHNDOVER_NUGHRNCBSCSUCC AS NUGHRNCBSCSUCC,
	UGHNDOVER_NUGHNDSDTOT AS NUGHNDSDTOT,
	UGHNDOVER_NUGHNDSDSUCC AS NUGHNDSDSUCC,
	UGHNDOVER_NUGHNDSTTOT AS NUGHNDSTTOT,
	UGHNDOVER_NUGHNDSTSUCC AS NUGHNDSTSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UGHNDOVER_NUGHNDRRQDTOT AS NUGHNDRRQDTOT,
	UGHNDOVER_NUGHNDREQTOT AS NUGHNDREQTOT,
	UGHNDOVER_NUGHNDREQSUCC AS NUGHNDREQSUCC,
	UGHNDOVER_NUGHNDCMDTOT AS NUGHNDCMDTOT,
	UGHNDOVER_NUGHNDDGSSUCC AS NUGHNDDGSSUCC,
	UGHNDOVER_NUGHNDCGSSUCC AS NUGHNDCGSSUCC,
	UGHNDOVER_NUGHNDATTSUCC AS NUGHNDATTSUCC,
	UGHNDOVER_NUGHNDRELERR AS NUGHNDRELERR,
	UGHNDOVER_NUGHRNCBSCTOT AS NUGHRNCBSCTOT,
	UGHNDOVER_NUGHRNCBSCSUCC AS NUGHRNCBSCSUCC,
	UGHNDOVER_NUGHNDSDTOT AS NUGHNDSDTOT,
	UGHNDOVER_NUGHNDSDSUCC AS NUGHNDSDSUCC,
	UGHNDOVER_NUGHNDSTTOT AS NUGHNDSTTOT,
	UGHNDOVER_NUGHNDSTSUCC AS NUGHNDSTSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

