---=======================
--------------- 01
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UPDLOCAT_NLOCNRGTOT AS NLOCNRGTOT,
	UPDLOCAT_NLOCIMSERR AS NLOCIMSERR,
	UPDLOCAT_NLOCOLDTOT AS NLOCOLDTOT,
	UPDLOCAT_NLOCPERTOT AS NLOCPERTOT,
	UPDLOCAT_NLOCUPDSUCC AS NLOCUPDSUCC,
	UPDLOCAT_NLOCATTTOT AS NLOCATTTOT,
	UPDLOCAT_NLOCDETTOT AS NLOCDETTOT,
	UPDLOCAT_NLOCNRGSUCC AS NLOCNRGSUCC,
	UPDLOCAT_NLOCIDTTOT AS NLOCIDTTOT,
	UPDLOCAT_NLOCNRRTOT AS NLOCNRRTOT,
	UPDLOCAT_NLOCOLDSUCC AS NLOCOLDSUCC,
	UPDLOCAT_NLOCREGSERR AS NLOCREGSERR,
	UPDLOCAT_NLOCIMS2ERR AS NLOCIMS2ERR,
	UPDLOCAT_NLOCNRG2SUCC AS NLOCNRG2SUCC,
	UPDLOCAT_NLOCOLD2SUCC AS NLOCOLD2SUCC,
	UPDLOCAT_NLOCDET2TOT AS NLOCDET2TOT,
	UPDLOCAT_NLOCNRG2TOT AS NLOCNRG2TOT,
	UPDLOCAT_NLOCOLD2TOT AS NLOCOLD2TOT,
	UPDLOCAT_NLOCATT2TOT AS NLOCATT2TOT,
	UPDLOCAT_NLOCGPRSTOT AS NLOCGPRSTOT,
	UPDLOCAT_NLOCGPRSSUCC AS NLOCGPRSSUCC,
	UPDLOCAT_NLOCCONGSUCC AS NLOCCONGSUCC,
	UPDLOCAT_NLOCPUTOTNEW AS NLOCPUTOTNEW,
	UPDLOCAT_NLOCPUNEWCON AS NLOCPUNEWCON,
	UPDLOCAT_NLOCPUOLDCON AS NLOCPUOLDCON,
	UPDLOCAT_NREGNOTRSUCC AS NREGNOTRSUCC,
	UPDLOCAT_NLNOLDTOT AS NLNOLDTOT,
	UPDLOCAT_NLNOLDSUCC AS NLNOLDSUCC,
	UPDLOCAT_NLOLDIMSUCC AS NLOLDIMSUCC,
	UPDLOCAT_NLPERSUCC AS NLPERSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_01
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 02
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UPDLOCAT_NLOCNRGTOT AS NLOCNRGTOT,
	UPDLOCAT_NLOCIMSERR AS NLOCIMSERR,
	UPDLOCAT_NLOCOLDTOT AS NLOCOLDTOT,
	UPDLOCAT_NLOCPERTOT AS NLOCPERTOT,
	UPDLOCAT_NLOCUPDSUCC AS NLOCUPDSUCC,
	UPDLOCAT_NLOCATTTOT AS NLOCATTTOT,
	UPDLOCAT_NLOCDETTOT AS NLOCDETTOT,
	UPDLOCAT_NLOCNRGSUCC AS NLOCNRGSUCC,
	UPDLOCAT_NLOCIDTTOT AS NLOCIDTTOT,
	UPDLOCAT_NLOCNRRTOT AS NLOCNRRTOT,
	UPDLOCAT_NLOCOLDSUCC AS NLOCOLDSUCC,
	UPDLOCAT_NLOCREGSERR AS NLOCREGSERR,
	UPDLOCAT_NLOCIMS2ERR AS NLOCIMS2ERR,
	UPDLOCAT_NLOCNRG2SUCC AS NLOCNRG2SUCC,
	UPDLOCAT_NLOCOLD2SUCC AS NLOCOLD2SUCC,
	UPDLOCAT_NLOCDET2TOT AS NLOCDET2TOT,
	UPDLOCAT_NLOCNRG2TOT AS NLOCNRG2TOT,
	UPDLOCAT_NLOCOLD2TOT AS NLOCOLD2TOT,
	UPDLOCAT_NLOCATT2TOT AS NLOCATT2TOT,
	UPDLOCAT_NLOCGPRSTOT AS NLOCGPRSTOT,
	UPDLOCAT_NLOCGPRSSUCC AS NLOCGPRSSUCC,
	UPDLOCAT_NLOCCONGSUCC AS NLOCCONGSUCC,
	UPDLOCAT_NLOCPUTOTNEW AS NLOCPUTOTNEW,
	UPDLOCAT_NLOCPUNEWCON AS NLOCPUNEWCON,
	UPDLOCAT_NLOCPUOLDCON AS NLOCPUOLDCON,
	UPDLOCAT_NREGNOTRSUCC AS NREGNOTRSUCC,
	UPDLOCAT_NLNOLDTOT AS NLNOLDTOT,
	UPDLOCAT_NLNOLDSUCC AS NLNOLDSUCC,
	UPDLOCAT_NLOLDIMSUCC AS NLOLDIMSUCC,
	UPDLOCAT_NLPERSUCC AS NLPERSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_02
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 03
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UPDLOCAT_NLOCNRGTOT AS NLOCNRGTOT,
	UPDLOCAT_NLOCIMSERR AS NLOCIMSERR,
	UPDLOCAT_NLOCOLDTOT AS NLOCOLDTOT,
	UPDLOCAT_NLOCPERTOT AS NLOCPERTOT,
	UPDLOCAT_NLOCUPDSUCC AS NLOCUPDSUCC,
	UPDLOCAT_NLOCATTTOT AS NLOCATTTOT,
	UPDLOCAT_NLOCDETTOT AS NLOCDETTOT,
	UPDLOCAT_NLOCNRGSUCC AS NLOCNRGSUCC,
	UPDLOCAT_NLOCIDTTOT AS NLOCIDTTOT,
	UPDLOCAT_NLOCNRRTOT AS NLOCNRRTOT,
	UPDLOCAT_NLOCOLDSUCC AS NLOCOLDSUCC,
	UPDLOCAT_NLOCREGSERR AS NLOCREGSERR,
	UPDLOCAT_NLOCIMS2ERR AS NLOCIMS2ERR,
	UPDLOCAT_NLOCNRG2SUCC AS NLOCNRG2SUCC,
	UPDLOCAT_NLOCOLD2SUCC AS NLOCOLD2SUCC,
	UPDLOCAT_NLOCDET2TOT AS NLOCDET2TOT,
	UPDLOCAT_NLOCNRG2TOT AS NLOCNRG2TOT,
	UPDLOCAT_NLOCOLD2TOT AS NLOCOLD2TOT,
	UPDLOCAT_NLOCATT2TOT AS NLOCATT2TOT,
	UPDLOCAT_NLOCGPRSTOT AS NLOCGPRSTOT,
	UPDLOCAT_NLOCGPRSSUCC AS NLOCGPRSSUCC,
	UPDLOCAT_NLOCCONGSUCC AS NLOCCONGSUCC,
	UPDLOCAT_NLOCPUTOTNEW AS NLOCPUTOTNEW,
	UPDLOCAT_NLOCPUNEWCON AS NLOCPUNEWCON,
	UPDLOCAT_NLOCPUOLDCON AS NLOCPUOLDCON,
	UPDLOCAT_NREGNOTRSUCC AS NREGNOTRSUCC,
	UPDLOCAT_NLNOLDTOT AS NLNOLDTOT,
	UPDLOCAT_NLNOLDSUCC AS NLNOLDSUCC,
	UPDLOCAT_NLOLDIMSUCC AS NLOLDIMSUCC,
	UPDLOCAT_NLPERSUCC AS NLPERSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_03
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 04
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UPDLOCAT_NLOCNRGTOT AS NLOCNRGTOT,
	UPDLOCAT_NLOCIMSERR AS NLOCIMSERR,
	UPDLOCAT_NLOCOLDTOT AS NLOCOLDTOT,
	UPDLOCAT_NLOCPERTOT AS NLOCPERTOT,
	UPDLOCAT_NLOCUPDSUCC AS NLOCUPDSUCC,
	UPDLOCAT_NLOCATTTOT AS NLOCATTTOT,
	UPDLOCAT_NLOCDETTOT AS NLOCDETTOT,
	UPDLOCAT_NLOCNRGSUCC AS NLOCNRGSUCC,
	UPDLOCAT_NLOCIDTTOT AS NLOCIDTTOT,
	UPDLOCAT_NLOCNRRTOT AS NLOCNRRTOT,
	UPDLOCAT_NLOCOLDSUCC AS NLOCOLDSUCC,
	UPDLOCAT_NLOCREGSERR AS NLOCREGSERR,
	UPDLOCAT_NLOCIMS2ERR AS NLOCIMS2ERR,
	UPDLOCAT_NLOCNRG2SUCC AS NLOCNRG2SUCC,
	UPDLOCAT_NLOCOLD2SUCC AS NLOCOLD2SUCC,
	UPDLOCAT_NLOCDET2TOT AS NLOCDET2TOT,
	UPDLOCAT_NLOCNRG2TOT AS NLOCNRG2TOT,
	UPDLOCAT_NLOCOLD2TOT AS NLOCOLD2TOT,
	UPDLOCAT_NLOCATT2TOT AS NLOCATT2TOT,
	UPDLOCAT_NLOCGPRSTOT AS NLOCGPRSTOT,
	UPDLOCAT_NLOCGPRSSUCC AS NLOCGPRSSUCC,
	UPDLOCAT_NLOCCONGSUCC AS NLOCCONGSUCC,
	UPDLOCAT_NLOCPUTOTNEW AS NLOCPUTOTNEW,
	UPDLOCAT_NLOCPUNEWCON AS NLOCPUNEWCON,
	UPDLOCAT_NLOCPUOLDCON AS NLOCPUOLDCON,
	UPDLOCAT_NREGNOTRSUCC AS NREGNOTRSUCC,
	UPDLOCAT_NLNOLDTOT AS NLNOLDTOT,
	UPDLOCAT_NLNOLDSUCC AS NLNOLDSUCC,
	UPDLOCAT_NLOLDIMSUCC AS NLOLDIMSUCC,
	UPDLOCAT_NLPERSUCC AS NLPERSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_04
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 05
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UPDLOCAT_NLOCNRGTOT AS NLOCNRGTOT,
	UPDLOCAT_NLOCIMSERR AS NLOCIMSERR,
	UPDLOCAT_NLOCOLDTOT AS NLOCOLDTOT,
	UPDLOCAT_NLOCPERTOT AS NLOCPERTOT,
	UPDLOCAT_NLOCUPDSUCC AS NLOCUPDSUCC,
	UPDLOCAT_NLOCATTTOT AS NLOCATTTOT,
	UPDLOCAT_NLOCDETTOT AS NLOCDETTOT,
	UPDLOCAT_NLOCNRGSUCC AS NLOCNRGSUCC,
	UPDLOCAT_NLOCIDTTOT AS NLOCIDTTOT,
	UPDLOCAT_NLOCNRRTOT AS NLOCNRRTOT,
	UPDLOCAT_NLOCOLDSUCC AS NLOCOLDSUCC,
	UPDLOCAT_NLOCREGSERR AS NLOCREGSERR,
	UPDLOCAT_NLOCIMS2ERR AS NLOCIMS2ERR,
	UPDLOCAT_NLOCNRG2SUCC AS NLOCNRG2SUCC,
	UPDLOCAT_NLOCOLD2SUCC AS NLOCOLD2SUCC,
	UPDLOCAT_NLOCDET2TOT AS NLOCDET2TOT,
	UPDLOCAT_NLOCNRG2TOT AS NLOCNRG2TOT,
	UPDLOCAT_NLOCOLD2TOT AS NLOCOLD2TOT,
	UPDLOCAT_NLOCATT2TOT AS NLOCATT2TOT,
	UPDLOCAT_NLOCGPRSTOT AS NLOCGPRSTOT,
	UPDLOCAT_NLOCGPRSSUCC AS NLOCGPRSSUCC,
	UPDLOCAT_NLOCCONGSUCC AS NLOCCONGSUCC,
	UPDLOCAT_NLOCPUTOTNEW AS NLOCPUTOTNEW,
	UPDLOCAT_NLOCPUNEWCON AS NLOCPUNEWCON,
	UPDLOCAT_NLOCPUOLDCON AS NLOCPUOLDCON,
	UPDLOCAT_NREGNOTRSUCC AS NREGNOTRSUCC,
	UPDLOCAT_NLNOLDTOT AS NLNOLDTOT,
	UPDLOCAT_NLNOLDSUCC AS NLNOLDSUCC,
	UPDLOCAT_NLOLDIMSUCC AS NLOLDIMSUCC,
	UPDLOCAT_NLPERSUCC AS NLPERSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_05
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 06
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UPDLOCAT_NLOCNRGTOT AS NLOCNRGTOT,
	UPDLOCAT_NLOCIMSERR AS NLOCIMSERR,
	UPDLOCAT_NLOCOLDTOT AS NLOCOLDTOT,
	UPDLOCAT_NLOCPERTOT AS NLOCPERTOT,
	UPDLOCAT_NLOCUPDSUCC AS NLOCUPDSUCC,
	UPDLOCAT_NLOCATTTOT AS NLOCATTTOT,
	UPDLOCAT_NLOCDETTOT AS NLOCDETTOT,
	UPDLOCAT_NLOCNRGSUCC AS NLOCNRGSUCC,
	UPDLOCAT_NLOCIDTTOT AS NLOCIDTTOT,
	UPDLOCAT_NLOCNRRTOT AS NLOCNRRTOT,
	UPDLOCAT_NLOCOLDSUCC AS NLOCOLDSUCC,
	UPDLOCAT_NLOCREGSERR AS NLOCREGSERR,
	UPDLOCAT_NLOCIMS2ERR AS NLOCIMS2ERR,
	UPDLOCAT_NLOCNRG2SUCC AS NLOCNRG2SUCC,
	UPDLOCAT_NLOCOLD2SUCC AS NLOCOLD2SUCC,
	UPDLOCAT_NLOCDET2TOT AS NLOCDET2TOT,
	UPDLOCAT_NLOCNRG2TOT AS NLOCNRG2TOT,
	UPDLOCAT_NLOCOLD2TOT AS NLOCOLD2TOT,
	UPDLOCAT_NLOCATT2TOT AS NLOCATT2TOT,
	UPDLOCAT_NLOCGPRSTOT AS NLOCGPRSTOT,
	UPDLOCAT_NLOCGPRSSUCC AS NLOCGPRSSUCC,
	UPDLOCAT_NLOCCONGSUCC AS NLOCCONGSUCC,
	UPDLOCAT_NLOCPUTOTNEW AS NLOCPUTOTNEW,
	UPDLOCAT_NLOCPUNEWCON AS NLOCPUNEWCON,
	UPDLOCAT_NLOCPUOLDCON AS NLOCPUOLDCON,
	UPDLOCAT_NREGNOTRSUCC AS NREGNOTRSUCC,
	UPDLOCAT_NLNOLDTOT AS NLNOLDTOT,
	UPDLOCAT_NLNOLDSUCC AS NLNOLDSUCC,
	UPDLOCAT_NLOLDIMSUCC AS NLOLDIMSUCC,
	UPDLOCAT_NLPERSUCC AS NLPERSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_06
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
UNION ALL

---=======================
--------------- 07
SELECT
	ELEM AS NE,
	MOID as MO,
	DATETIME_ID as [TIME],
	CASE
		WHEN PERIOD_DURATION = 60 THEN 1
		WHEN PERIOD_DURATION = 15 THEN 0
	END AS RES,
	PERIOD_DURATION AS RPL,
--------------	
	PERIOD_DURATION AS CFAIL,
	UPDLOCAT_NLOCNRGTOT AS NLOCNRGTOT,
	UPDLOCAT_NLOCIMSERR AS NLOCIMSERR,
	UPDLOCAT_NLOCOLDTOT AS NLOCOLDTOT,
	UPDLOCAT_NLOCPERTOT AS NLOCPERTOT,
	UPDLOCAT_NLOCUPDSUCC AS NLOCUPDSUCC,
	UPDLOCAT_NLOCATTTOT AS NLOCATTTOT,
	UPDLOCAT_NLOCDETTOT AS NLOCDETTOT,
	UPDLOCAT_NLOCNRGSUCC AS NLOCNRGSUCC,
	UPDLOCAT_NLOCIDTTOT AS NLOCIDTTOT,
	UPDLOCAT_NLOCNRRTOT AS NLOCNRRTOT,
	UPDLOCAT_NLOCOLDSUCC AS NLOCOLDSUCC,
	UPDLOCAT_NLOCREGSERR AS NLOCREGSERR,
	UPDLOCAT_NLOCIMS2ERR AS NLOCIMS2ERR,
	UPDLOCAT_NLOCNRG2SUCC AS NLOCNRG2SUCC,
	UPDLOCAT_NLOCOLD2SUCC AS NLOCOLD2SUCC,
	UPDLOCAT_NLOCDET2TOT AS NLOCDET2TOT,
	UPDLOCAT_NLOCNRG2TOT AS NLOCNRG2TOT,
	UPDLOCAT_NLOCOLD2TOT AS NLOCOLD2TOT,
	UPDLOCAT_NLOCATT2TOT AS NLOCATT2TOT,
	UPDLOCAT_NLOCGPRSTOT AS NLOCGPRSTOT,
	UPDLOCAT_NLOCGPRSSUCC AS NLOCGPRSSUCC,
	UPDLOCAT_NLOCCONGSUCC AS NLOCCONGSUCC,
	UPDLOCAT_NLOCPUTOTNEW AS NLOCPUTOTNEW,
	UPDLOCAT_NLOCPUNEWCON AS NLOCPUNEWCON,
	UPDLOCAT_NLOCPUOLDCON AS NLOCPUOLDCON,
	UPDLOCAT_NREGNOTRSUCC AS NREGNOTRSUCC,
	UPDLOCAT_NLNOLDTOT AS NLNOLDTOT,
	UPDLOCAT_NLNOLDSUCC AS NLNOLDSUCC,
	UPDLOCAT_NLOLDIMSUCC AS NLOLDIMSUCC,
	UPDLOCAT_NLPERSUCC AS NLPERSUCC
FROM
    dc.DC_E_CNAXE_MSC_RAW_07
---------------	
	WHERE DATETIME_ID >= (SELECT S_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND DATETIME_ID<(SELECT E_TIME FROM dcpublic.T_TIME_TRANSFER_D1) 
	AND PERIOD_DURATION=60 
	AND (ELEM LIKE 'M%' OR ELEM LIKE 'T%' OR ELEM LIKE 'H%') 
	AND ROWSTATUS!='DUPLICATE' 
	AND ROWSTATUS!='SUSPECTED'
	
--- End ---

