import pyautogui
import time

pyautogui.hotkey('winleft', 'r')
time.sleep(1)
pyautogui.typewrite('inetcpl.cpl')
pyautogui.hotkey('enter')
time.sleep(2)
pyautogui.hotkey('ctrl','tab')
pyautogui.hotkey('ctrl','tab')
pyautogui.hotkey('ctrl','tab')
pyautogui.hotkey('ctrl','tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('enter')
time.sleep(1)
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('space')
time.sleep(2)
pyautogui.hotkey('enter')
time.sleep(1)
pyautogui.hotkey('esc')