import pyautogui
import time

pyautogui.hotkey('alt', 'tab')
time.sleep(1)
pyautogui.click(button='right')
time.sleep(1)
pyautogui.press('p')
time.sleep(1)
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('home')
pyautogui.keyDown('shift')
pyautogui.press('right', presses=42)
pyautogui.keyUp('shift')
pyautogui.hotkey('delete')
pyautogui.write('D:\OSS-SSS\FTP_CSV_IP_10.167.26.102\HOST04')
time.sleep(1)
pyautogui.hotkey('home')
pyautogui.hotkey('shift','end')
pyautogui.hotkey('ctrl','c')
pyautogui.hotkey('enter')
pyautogui.hotkey('enter')
